package notification

import (
	"bytes"
	"encoding/json"
	"fmt"
	"html/template"

	"github.com/ma111e/downlink/pkg/utils"
)

// LandingProfile is one profile shown on the public root landing page and listed
// in profiles.json. Subdir is the (resolved) output directory the profile
// publishes under, used as the relative link target.
type LandingProfile struct {
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
	Icon        string `json:"icon,omitempty"`
	Subdir      string `json:"subdir"`
}

// ProfilesJSON serializes the landing profiles for profiles.json (consumed by
// the in-page profile switcher and any external tooling).
func ProfilesJSON(profiles []LandingProfile) ([]byte, error) {
	return json.MarshalIndent(struct {
		Profiles []LandingProfile `json:"profiles"`
	}{Profiles: profiles}, "", "  ")
}

// landingCSS is the landing page stylesheet, split out into templates/landing.css
// and injected via the styleCSS template func so it stays trusted (no CSS-context
// escaping).
var landingCSS = func() template.CSS {
	b, err := notificationTemplateFS.ReadFile("templates/landing.css")
	if err != nil {
		panic(fmt.Sprintf("read embedded landing.css: %v", err))
	}
	return template.CSS(utils.StripCSSComments(string(b)))
}()

// rootLandingTemplate is a small, self-contained landing page listing the public
// profiles and linking into each profile's section. It intentionally has no
// external assets so it works at the repo root regardless of layout.
var rootLandingTemplate = template.Must(template.New("landing").
	Funcs(template.FuncMap{"styleCSS": func() template.CSS { return landingCSS }}).
	Parse(`<!doctype html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Downlink — Profiles</title>
<link rel="icon" href="favicon.ico">
<style>{{styleCSS}}</style>
</head>
<body>
<div class="wrap">
  <h1>Downlink</h1>
  <p class="sub">Choose a profile.</p>
  <ul>
    {{range .Profiles}}
    <li><a class="card" href="{{.Subdir}}/">
      {{if .Icon}}<span class="icon">{{.Icon}}</span>{{end}}
      <span>
        <span class="name">{{.Name}}</span>
        {{if .Description}}<span class="desc">{{.Description}}</span>{{end}}
      </span>
    </a></li>
    {{end}}
  </ul>
  <footer>Generated by Downlink</footer>
</div>
</body>
</html>
`))

// renderRootLanding builds the public landing page HTML listing the profiles.
func renderRootLanding(profiles []LandingProfile) ([]byte, error) {
	var buf bytes.Buffer
	if err := rootLandingTemplate.Execute(&buf, struct{ Profiles []LandingProfile }{Profiles: profiles}); err != nil {
		return nil, fmt.Errorf("render root landing: %w", err)
	}
	return buf.Bytes(), nil
}
