package notification

import (
	"bytes"
	"encoding/json"
	"fmt"
	"html/template"
)

// LandingProfile is one profile shown on the public root landing page and listed
// in profiles.json. Subdir is the (resolved) output directory the profile
// publishes under, used as the relative link target.
type LandingProfile struct {
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
	Icon        string `json:"icon,omitempty"`
	Subdir      string `json:"subdir"`
}

// ProfilesJSON serializes the landing profiles for profiles.json (consumed by
// the in-page profile switcher and any external tooling).
func ProfilesJSON(profiles []LandingProfile) ([]byte, error) {
	return json.MarshalIndent(struct {
		Profiles []LandingProfile `json:"profiles"`
	}{Profiles: profiles}, "", "  ")
}

// rootLandingTemplate is a small, self-contained landing page listing the public
// profiles and linking into each profile's section. It intentionally has no
// external assets so it works at the repo root regardless of layout.
var rootLandingTemplate = template.Must(template.New("landing").Parse(`<!doctype html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Downlink — Profiles</title>
<link rel="icon" href="favicon.ico">
<style>
  :root { color-scheme: dark; }
  body { margin:0; font:16px/1.5 system-ui,sans-serif; background:#0f1115; color:#e7e9ee; }
  .wrap { max-width:720px; margin:0 auto; padding:3rem 1.25rem; }
  h1 { font-size:1.6rem; margin:0 0 .25rem; }
  p.sub { color:#9aa3b2; margin:0 0 2rem; }
  ul { list-style:none; margin:0; padding:0; display:grid; gap:.75rem; }
  a.card { display:flex; gap:.9rem; align-items:flex-start; text-decoration:none;
           color:inherit; background:#171a21; border:1px solid #242833; border-radius:12px;
           padding:1rem 1.1rem; transition:border-color .15s, transform .05s; }
  a.card:hover { border-color:#3a86ff; }
  a.card:active { transform:translateY(1px); }
  .icon { font-size:1.6rem; line-height:1; }
  .name { font-weight:600; }
  .desc { color:#9aa3b2; font-size:.92rem; margin-top:.15rem; }
  footer { color:#5b6472; font-size:.8rem; margin-top:2.5rem; }
</style>
</head>
<body>
<div class="wrap">
  <h1>Downlink</h1>
  <p class="sub">Choose a profile.</p>
  <ul>
    {{range .Profiles}}
    <li><a class="card" href="{{.Subdir}}/">
      {{if .Icon}}<span class="icon">{{.Icon}}</span>{{end}}
      <span>
        <span class="name">{{.Name}}</span>
        {{if .Description}}<span class="desc">{{.Description}}</span>{{end}}
      </span>
    </a></li>
    {{end}}
  </ul>
  <footer>Generated by Downlink</footer>
</div>
</body>
</html>
`))

// renderRootLanding builds the public landing page HTML listing the profiles.
func renderRootLanding(profiles []LandingProfile) ([]byte, error) {
	var buf bytes.Buffer
	if err := rootLandingTemplate.Execute(&buf, struct{ Profiles []LandingProfile }{Profiles: profiles}); err != nil {
		return nil, fmt.Errorf("render root landing: %w", err)
	}
	return buf.Bytes(), nil
}
