// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: analysis.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ArticleAnalysis represents an analysis result from an LLM provider for an article
type ReferencedReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Publisher     string                 `protobuf:"bytes,3,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Context       string                 `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferencedReport) Reset() {
	*x = ReferencedReport{}
	mi := &file_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferencedReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferencedReport) ProtoMessage() {}

func (x *ReferencedReport) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferencedReport.ProtoReflect.Descriptor instead.
func (*ReferencedReport) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *ReferencedReport) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReferencedReport) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ReferencedReport) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *ReferencedReport) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type ArticleAnalysis struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ArticleId              string                 `protobuf:"bytes,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	ProviderType           string                 `protobuf:"bytes,3,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	ModelName              string                 `protobuf:"bytes,4,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ImportanceScore        int32                  `protobuf:"varint,5,opt,name=importance_score,json=importanceScore,proto3" json:"importance_score,omitempty"`
	KeyPoints              []string               `protobuf:"bytes,6,rep,name=key_points,json=keyPoints,proto3" json:"key_points,omitempty"`
	Insights               []string               `protobuf:"bytes,7,rep,name=insights,proto3" json:"insights,omitempty"`
	Tldr                   string                 `protobuf:"bytes,18,opt,name=tldr,proto3" json:"tldr,omitempty"`
	Justification          string                 `protobuf:"bytes,8,opt,name=justification,proto3" json:"justification,omitempty"`
	BriefOverview          string                 `protobuf:"bytes,9,opt,name=brief_overview,json=briefOverview,proto3" json:"brief_overview,omitempty"`
	StandardSynthesis      string                 `protobuf:"bytes,10,opt,name=standard_synthesis,json=standardSynthesis,proto3" json:"standard_synthesis,omitempty"`
	ComprehensiveSynthesis string                 `protobuf:"bytes,11,opt,name=comprehensive_synthesis,json=comprehensiveSynthesis,proto3" json:"comprehensive_synthesis,omitempty"`
	ThinkingProcess        string                 `protobuf:"bytes,12,opt,name=thinking_process,json=thinkingProcess,proto3" json:"thinking_process,omitempty"`
	RawResponse            string                 `protobuf:"bytes,13,opt,name=raw_response,json=rawResponse,proto3" json:"raw_response,omitempty"`
	CreatedAt              *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	KeyPointsJson          string                 `protobuf:"bytes,15,opt,name=key_points_json,json=keyPointsJson,proto3" json:"key_points_json,omitempty"`
	InsightsJson           string                 `protobuf:"bytes,16,opt,name=insights_json,json=insightsJson,proto3" json:"insights_json,omitempty"`
	Article                *Article               `protobuf:"bytes,17,opt,name=article,proto3,oneof" json:"article,omitempty"`
	ReferencedReports      []*ReferencedReport    `protobuf:"bytes,19,rep,name=referenced_reports,json=referencedReports,proto3" json:"referenced_reports,omitempty"`
	ReferencedReportsJson  string                 `protobuf:"bytes,20,opt,name=referenced_reports_json,json=referencedReportsJson,proto3" json:"referenced_reports_json,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ArticleAnalysis) Reset() {
	*x = ArticleAnalysis{}
	mi := &file_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleAnalysis) ProtoMessage() {}

func (x *ArticleAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleAnalysis.ProtoReflect.Descriptor instead.
func (*ArticleAnalysis) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *ArticleAnalysis) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArticleAnalysis) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *ArticleAnalysis) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *ArticleAnalysis) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ArticleAnalysis) GetImportanceScore() int32 {
	if x != nil {
		return x.ImportanceScore
	}
	return 0
}

func (x *ArticleAnalysis) GetKeyPoints() []string {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

func (x *ArticleAnalysis) GetInsights() []string {
	if x != nil {
		return x.Insights
	}
	return nil
}

func (x *ArticleAnalysis) GetTldr() string {
	if x != nil {
		return x.Tldr
	}
	return ""
}

func (x *ArticleAnalysis) GetJustification() string {
	if x != nil {
		return x.Justification
	}
	return ""
}

func (x *ArticleAnalysis) GetBriefOverview() string {
	if x != nil {
		return x.BriefOverview
	}
	return ""
}

func (x *ArticleAnalysis) GetStandardSynthesis() string {
	if x != nil {
		return x.StandardSynthesis
	}
	return ""
}

func (x *ArticleAnalysis) GetComprehensiveSynthesis() string {
	if x != nil {
		return x.ComprehensiveSynthesis
	}
	return ""
}

func (x *ArticleAnalysis) GetThinkingProcess() string {
	if x != nil {
		return x.ThinkingProcess
	}
	return ""
}

func (x *ArticleAnalysis) GetRawResponse() string {
	if x != nil {
		return x.RawResponse
	}
	return ""
}

func (x *ArticleAnalysis) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ArticleAnalysis) GetKeyPointsJson() string {
	if x != nil {
		return x.KeyPointsJson
	}
	return ""
}

func (x *ArticleAnalysis) GetInsightsJson() string {
	if x != nil {
		return x.InsightsJson
	}
	return ""
}

func (x *ArticleAnalysis) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *ArticleAnalysis) GetReferencedReports() []*ReferencedReport {
	if x != nil {
		return x.ReferencedReports
	}
	return nil
}

func (x *ArticleAnalysis) GetReferencedReportsJson() string {
	if x != nil {
		return x.ReferencedReportsJson
	}
	return ""
}

// GetAllArticleAnalysesRequest represents a request to retrieve all analysis results for a specific article
type GetAllArticleAnalysesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllArticleAnalysesRequest) Reset() {
	*x = GetAllArticleAnalysesRequest{}
	mi := &file_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllArticleAnalysesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllArticleAnalysesRequest) ProtoMessage() {}

func (x *GetAllArticleAnalysesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllArticleAnalysesRequest.ProtoReflect.Descriptor instead.
func (*GetAllArticleAnalysesRequest) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllArticleAnalysesRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

// GetAllArticleAnalysesResponse represents the response with all analysis results for a specific article
type GetAllArticleAnalysesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analyses      []*ArticleAnalysis     `protobuf:"bytes,1,rep,name=analyses,proto3" json:"analyses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllArticleAnalysesResponse) Reset() {
	*x = GetAllArticleAnalysesResponse{}
	mi := &file_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllArticleAnalysesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllArticleAnalysesResponse) ProtoMessage() {}

func (x *GetAllArticleAnalysesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllArticleAnalysesResponse.ProtoReflect.Descriptor instead.
func (*GetAllArticleAnalysesResponse) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllArticleAnalysesResponse) GetAnalyses() []*ArticleAnalysis {
	if x != nil {
		return x.Analyses
	}
	return nil
}

type GetAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalysisRequest) Reset() {
	*x = GetAnalysisRequest{}
	mi := &file_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisRequest) ProtoMessage() {}

func (x *GetAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisRequest.ProtoReflect.Descriptor instead.
func (*GetAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{4}
}

func (x *GetAnalysisRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

var File_analysis_proto protoreflect.FileDescriptor

const file_analysis_proto_rawDesc = "" +
	"\n" +
	"\x0eanalysis.proto\x12\bdownlink\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0earticles.proto\"r\n" +
	"\x10ReferencedReport\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1c\n" +
	"\tpublisher\x18\x03 \x01(\tR\tpublisher\x12\x18\n" +
	"\acontext\x18\x04 \x01(\tR\acontext\"\xca\x06\n" +
	"\x0fArticleAnalysis\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"article_id\x18\x02 \x01(\tR\tarticleId\x12#\n" +
	"\rprovider_type\x18\x03 \x01(\tR\fproviderType\x12\x1d\n" +
	"\n" +
	"model_name\x18\x04 \x01(\tR\tmodelName\x12)\n" +
	"\x10importance_score\x18\x05 \x01(\x05R\x0fimportanceScore\x12\x1d\n" +
	"\n" +
	"key_points\x18\x06 \x03(\tR\tkeyPoints\x12\x1a\n" +
	"\binsights\x18\a \x03(\tR\binsights\x12\x12\n" +
	"\x04tldr\x18\x12 \x01(\tR\x04tldr\x12$\n" +
	"\rjustification\x18\b \x01(\tR\rjustification\x12%\n" +
	"\x0ebrief_overview\x18\t \x01(\tR\rbriefOverview\x12-\n" +
	"\x12standard_synthesis\x18\n" +
	" \x01(\tR\x11standardSynthesis\x127\n" +
	"\x17comprehensive_synthesis\x18\v \x01(\tR\x16comprehensiveSynthesis\x12)\n" +
	"\x10thinking_process\x18\f \x01(\tR\x0fthinkingProcess\x12!\n" +
	"\fraw_response\x18\r \x01(\tR\vrawResponse\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12&\n" +
	"\x0fkey_points_json\x18\x0f \x01(\tR\rkeyPointsJson\x12#\n" +
	"\rinsights_json\x18\x10 \x01(\tR\finsightsJson\x120\n" +
	"\aarticle\x18\x11 \x01(\v2\x11.downlink.ArticleH\x00R\aarticle\x88\x01\x01\x12I\n" +
	"\x12referenced_reports\x18\x13 \x03(\v2\x1a.downlink.ReferencedReportR\x11referencedReports\x126\n" +
	"\x17referenced_reports_json\x18\x14 \x01(\tR\x15referencedReportsJsonB\n" +
	"\n" +
	"\b_article\"=\n" +
	"\x1cGetAllArticleAnalysesRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\"V\n" +
	"\x1dGetAllArticleAnalysesResponse\x125\n" +
	"\banalyses\x18\x01 \x03(\v2\x19.downlink.ArticleAnalysisR\banalyses\"3\n" +
	"\x12GetAnalysisRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId2\xc7\x01\n" +
	"\x0fAnalysisService\x12j\n" +
	"\x15GetAllArticleAnalyses\x12&.downlink.GetAllArticleAnalysesRequest\x1a'.downlink.GetAllArticleAnalysesResponse\"\x00\x12H\n" +
	"\vGetAnalysis\x12\x1c.downlink.GetAnalysisRequest\x1a\x19.downlink.ArticleAnalysis\"\x00B\tZ\aprotos/b\x06proto3"

var (
	file_analysis_proto_rawDescOnce sync.Once
	file_analysis_proto_rawDescData []byte
)

func file_analysis_proto_rawDescGZIP() []byte {
	file_analysis_proto_rawDescOnce.Do(func() {
		file_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analysis_proto_rawDesc), len(file_analysis_proto_rawDesc)))
	})
	return file_analysis_proto_rawDescData
}

var file_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_analysis_proto_goTypes = []any{
	(*ReferencedReport)(nil),              // 0: downlink.ReferencedReport
	(*ArticleAnalysis)(nil),               // 1: downlink.ArticleAnalysis
	(*GetAllArticleAnalysesRequest)(nil),  // 2: downlink.GetAllArticleAnalysesRequest
	(*GetAllArticleAnalysesResponse)(nil), // 3: downlink.GetAllArticleAnalysesResponse
	(*GetAnalysisRequest)(nil),            // 4: downlink.GetAnalysisRequest
	(*timestamppb.Timestamp)(nil),         // 5: google.protobuf.Timestamp
	(*Article)(nil),                       // 6: downlink.Article
}
var file_analysis_proto_depIdxs = []int32{
	5, // 0: downlink.ArticleAnalysis.created_at:type_name -> google.protobuf.Timestamp
	6, // 1: downlink.ArticleAnalysis.article:type_name -> downlink.Article
	0, // 2: downlink.ArticleAnalysis.referenced_reports:type_name -> downlink.ReferencedReport
	1, // 3: downlink.GetAllArticleAnalysesResponse.analyses:type_name -> downlink.ArticleAnalysis
	2, // 4: downlink.AnalysisService.GetAllArticleAnalyses:input_type -> downlink.GetAllArticleAnalysesRequest
	4, // 5: downlink.AnalysisService.GetAnalysis:input_type -> downlink.GetAnalysisRequest
	3, // 6: downlink.AnalysisService.GetAllArticleAnalyses:output_type -> downlink.GetAllArticleAnalysesResponse
	1, // 7: downlink.AnalysisService.GetAnalysis:output_type -> downlink.ArticleAnalysis
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_analysis_proto_init() }
func file_analysis_proto_init() {
	if File_analysis_proto != nil {
		return
	}
	file_articles_proto_init()
	file_analysis_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analysis_proto_rawDesc), len(file_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analysis_proto_goTypes,
		DependencyIndexes: file_analysis_proto_depIdxs,
		MessageInfos:      file_analysis_proto_msgTypes,
	}.Build()
	File_analysis_proto = out.File
	file_analysis_proto_goTypes = nil
	file_analysis_proto_depIdxs = nil
}
