// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: articles.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Category represents an article category
type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Articles      []*Article             `protobuf:"bytes,4,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_articles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_articles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_articles_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Category) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Category) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

// Tag represents an article tag
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	UseCount      int32                  `protobuf:"varint,4,opt,name=use_count,json=useCount,proto3" json:"use_count,omitempty"`
	Articles      []*Article             `protobuf:"bytes,5,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_articles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_articles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_articles_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Tag) GetUseCount() int32 {
	if x != nil {
		return x.UseCount
	}
	return 0
}

func (x *Tag) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

// RelatedArticle represents a relationship between two articles
type RelatedArticle struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ArticleId        string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	RelatedArticleId string                 `protobuf:"bytes,2,opt,name=related_article_id,json=relatedArticleId,proto3" json:"related_article_id,omitempty"`
	RelationType     string                 `protobuf:"bytes,3,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	SimilarityScore  float64                `protobuf:"fixed64,4,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RelatedArticle) Reset() {
	*x = RelatedArticle{}
	mi := &file_articles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelatedArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatedArticle) ProtoMessage() {}

func (x *RelatedArticle) ProtoReflect() protoreflect.Message {
	mi := &file_articles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatedArticle.ProtoReflect.Descriptor instead.
func (*RelatedArticle) Descriptor() ([]byte, []int) {
	return file_articles_proto_rawDescGZIP(), []int{2}
}

func (x *RelatedArticle) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *RelatedArticle) GetRelatedArticleId() string {
	if x != nil {
		return x.RelatedArticleId
	}
	return ""
}

func (x *RelatedArticle) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *RelatedArticle) GetSimilarityScore() float64 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

// Article represents an article from a feed
type Article struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FeedId          string                 `protobuf:"bytes,2,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content         string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Link            string                 `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	PublishedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	FetchedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	Read            *bool                  `protobuf:"varint,8,opt,name=read,proto3,oneof" json:"read,omitempty"`
	Tags            []*Tag                 `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	CategoryName    *string                `protobuf:"bytes,10,opt,name=category_name,json=categoryName,proto3,oneof" json:"category_name,omitempty"`
	Category        *Category              `protobuf:"bytes,11,opt,name=category,proto3" json:"category,omitempty"`
	HeroImage       string                 `protobuf:"bytes,12,opt,name=hero_image,json=heroImage,proto3" json:"hero_image,omitempty"`
	Bookmarked      *bool                  `protobuf:"varint,13,opt,name=bookmarked,proto3,oneof" json:"bookmarked,omitempty"`
	RelatedArticles []*RelatedArticle      `protobuf:"bytes,14,rep,name=related_articles,json=relatedArticles,proto3" json:"related_articles,omitempty"`
	// Latest analysis importance score (0-100). Populated by ListArticles for list rendering;
	// unset (or 0) when no analysis exists. Not stored on the article record itself.
	LatestImportanceScore *int32 `protobuf:"varint,15,opt,name=latest_importance_score,json=latestImportanceScore,proto3,oneof" json:"latest_importance_score,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_articles_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_articles_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_articles_proto_rawDescGZIP(), []int{3}
}

func (x *Article) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Article) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Article) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Article) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Article) GetFetchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedAt
	}
	return nil
}

func (x *Article) GetRead() bool {
	if x != nil && x.Read != nil {
		return *x.Read
	}
	return false
}

func (x *Article) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Article) GetCategoryName() string {
	if x != nil && x.CategoryName != nil {
		return *x.CategoryName
	}
	return ""
}

func (x *Article) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Article) GetHeroImage() string {
	if x != nil {
		return x.HeroImage
	}
	return ""
}

func (x *Article) GetBookmarked() bool {
	if x != nil && x.Bookmarked != nil {
		return *x.Bookmarked
	}
	return false
}

func (x *Article) GetRelatedArticles() []*RelatedArticle {
	if x != nil {
		return x.RelatedArticles
	}
	return nil
}

func (x *Article) GetLatestImportanceScore() int32 {
	if x != nil && x.LatestImportanceScore != nil {
		return *x.LatestImportanceScore
	}
	return 0
}

// ArticleUpdate represents fields that can be updated for an article
type ArticleUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Read            *bool                  `protobuf:"varint,1,opt,name=read,proto3,oneof" json:"read,omitempty"`
	TagIds          []string               `protobuf:"bytes,2,rep,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	CategoryName    *string                `protobuf:"bytes,3,opt,name=category_name,json=categoryName,proto3,oneof" json:"category_name,omitempty"`
	HeroImage       *string                `protobuf:"bytes,4,opt,name=hero_image,json=heroImage,proto3,oneof" json:"hero_image,omitempty"`
	Bookmarked      *bool                  `protobuf:"varint,5,opt,name=bookmarked,proto3,oneof" json:"bookmarked,omitempty"`
	RelatedArticles []*RelatedArticle      `protobuf:"bytes,6,rep,name=related_articles,json=relatedArticles,proto3" json:"related_articles,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ArticleUpdate) Reset() {
	*x = ArticleUpdate{}
	mi := &file_articles_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleUpdate) ProtoMessage() {}

func (x *ArticleUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_articles_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleUpdate.ProtoReflect.Descriptor instead.
func (*ArticleUpdate) Descriptor() ([]byte, []int) {
	return file_articles_proto_rawDescGZIP(), []int{4}
}

func (x *ArticleUpdate) GetRead() bool {
	if x != nil && x.Read != nil {
		return *x.Read
	}
	return false
}

func (x *ArticleUpdate) GetTagIds() []string {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *ArticleUpdate) GetCategoryName() string {
	if x != nil && x.CategoryName != nil {
		return *x.CategoryName
	}
	return ""
}

func (x *ArticleUpdate) GetHeroImage() string {
	if x != nil && x.HeroImage != nil {
		return *x.HeroImage
	}
	return ""
}

func (x *ArticleUpdate) GetBookmarked() bool {
	if x != nil && x.Bookmarked != nil {
		return *x.Bookmarked
	}
	return false
}

func (x *ArticleUpdate) GetRelatedArticles() []*RelatedArticle {
	if x != nil {
		return x.RelatedArticles
	}
	return nil
}

// ArticleFilter represents filtering options for listing articles
type ArticleFilter struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UnreadOnly      bool                   `protobuf:"varint,1,opt,name=unread_only,json=unreadOnly,proto3" json:"unread_only,omitempty"`
	CategoryName    string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	TagId           string                 `protobuf:"bytes,3,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	BookmarkedOnly  bool                   `protobuf:"varint,4,opt,name=bookmarked_only,json=bookmarkedOnly,proto3" json:"bookmarked_only,omitempty"`
	RelatedToId     string                 `protobuf:"bytes,5,opt,name=related_to_id,json=relatedToId,proto3" json:"related_to_id,omitempty"`
	StartDate       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	FeedId          string                 `protobuf:"bytes,8,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	Offset          uint32                 `protobuf:"varint,9,opt,name=offset,proto3" json:"offset,omitempty"`
	ExcludeDigested bool                   `protobuf:"varint,10,opt,name=exclude_digested,json=excludeDigested,proto3" json:"exclude_digested,omitempty"`
	Limit           uint32                 `protobuf:"varint,11,opt,name=limit,proto3" json:"limit,omitempty"`
	Query           string                 `protobuf:"bytes,12,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ArticleFilter) Reset() {
	*x = ArticleFilter{}
	mi := &file_articles_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleFilter) ProtoMessage() {}

func (x *ArticleFilter) ProtoReflect() protoreflect.Message {
	mi := &file_articles_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleFilter.ProtoReflect.Descriptor instead.
func (*ArticleFilter) Descriptor() ([]byte, []int) {
	return file_articles_proto_rawDescGZIP(), []int{5}
}

func (x *ArticleFilter) GetUnreadOnly() bool {
	if x != nil {
		return x.UnreadOnly
	}
	return false
}

func (x *ArticleFilter) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ArticleFilter) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *ArticleFilter) GetBookmarkedOnly() bool {
	if x != nil {
		return x.BookmarkedOnly
	}
	return false
}

func (x *ArticleFilter) GetRelatedToId() string {
	if x != nil {
		return x.RelatedToId
	}
	return ""
}

func (x *ArticleFilter) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ArticleFilter) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *ArticleFilter) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

func (x *ArticleFilter) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ArticleFilter) GetExcludeDigested() bool {
	if x != nil {
		return x.ExcludeDigested
	}
	return false
}

func (x *ArticleFilter) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ArticleFilter) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// ListArticlesResponse represents the response with a list of articles
type ListArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesResponse) Reset() {
	*x = ListArticlesResponse{}
	mi := &file_articles_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesResponse) ProtoMessage() {}

func (x *ListArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesResponse.ProtoReflect.Descriptor instead.
func (*ListArticlesResponse) Descriptor() ([]byte, []int) {
	return file_articles_proto_rawDescGZIP(), []int{6}
}

func (x *ListArticlesResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

// ArticleCountsResponse represents exact sidebar counts for the current query scope.
type ArticleCountsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AllUnreadCount  int32                  `protobuf:"varint,1,opt,name=all_unread_count,json=allUnreadCount,proto3" json:"all_unread_count,omitempty"`
	BookmarkedCount int32                  `protobuf:"varint,2,opt,name=bookmarked_count,json=bookmarkedCount,proto3" json:"bookmarked_count,omitempty"`
	UnreadByFeed    map[string]int32       `protobuf:"bytes,3,rep,name=unread_by_feed,json=unreadByFeed,proto3" json:"unread_by_feed,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ArticleCountsResponse) Reset() {
	*x = ArticleCountsResponse{}
	mi := &file_articles_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleCountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleCountsResponse) ProtoMessage() {}

func (x *ArticleCountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleCountsResponse.ProtoReflect.Descriptor instead.
func (*ArticleCountsResponse) Descriptor() ([]byte, []int) {
	return file_articles_proto_rawDescGZIP(), []int{7}
}

func (x *ArticleCountsResponse) GetAllUnreadCount() int32 {
	if x != nil {
		return x.AllUnreadCount
	}
	return 0
}

func (x *ArticleCountsResponse) GetBookmarkedCount() int32 {
	if x != nil {
		return x.BookmarkedCount
	}
	return 0
}

func (x *ArticleCountsResponse) GetUnreadByFeed() map[string]int32 {
	if x != nil {
		return x.UnreadByFeed
	}
	return nil
}

// GetArticleRequest represents a request to retrieve a single article by Id
type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_articles_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_articles_proto_rawDescGZIP(), []int{8}
}

func (x *GetArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// UpdateArticleRequest represents a request to update an article
type UpdateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Update        *ArticleUpdate         `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_articles_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_articles_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateArticleRequest) GetUpdate() *ArticleUpdate {
	if x != nil {
		return x.Update
	}
	return nil
}

type MarkFeedReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedId        string                 `protobuf:"bytes,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkFeedReadRequest) Reset() {
	*x = MarkFeedReadRequest{}
	mi := &file_articles_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkFeedReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkFeedReadRequest) ProtoMessage() {}

func (x *MarkFeedReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkFeedReadRequest.ProtoReflect.Descriptor instead.
func (*MarkFeedReadRequest) Descriptor() ([]byte, []int) {
	return file_articles_proto_rawDescGZIP(), []int{10}
}

func (x *MarkFeedReadRequest) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

// GetOrCreateCategoryRequest represents a request to retrieve or create a category by name
type GetOrCreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrCreateCategoryRequest) Reset() {
	*x = GetOrCreateCategoryRequest{}
	mi := &file_articles_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateCategoryRequest) ProtoMessage() {}

func (x *GetOrCreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetOrCreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_articles_proto_rawDescGZIP(), []int{11}
}

func (x *GetOrCreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetOrCreateCategoryResponse represents the response with a category
type GetOrCreateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrCreateCategoryResponse) Reset() {
	*x = GetOrCreateCategoryResponse{}
	mi := &file_articles_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateCategoryResponse) ProtoMessage() {}

func (x *GetOrCreateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetOrCreateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_articles_proto_rawDescGZIP(), []int{12}
}

func (x *GetOrCreateCategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

var File_articles_proto protoreflect.FileDescriptor

const file_articles_proto_rawDesc = "" +
	"\n" +
	"\x0earticles.proto\x12\bdownlink\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"w\n" +
	"\bCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12-\n" +
	"\barticles\x18\x04 \x03(\v2\x11.downlink.ArticleR\barticles\"\x8b\x01\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x1b\n" +
	"\tuse_count\x18\x04 \x01(\x05R\buseCount\x12-\n" +
	"\barticles\x18\x05 \x03(\v2\x11.downlink.ArticleR\barticles\"\xad\x01\n" +
	"\x0eRelatedArticle\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12,\n" +
	"\x12related_article_id\x18\x02 \x01(\tR\x10relatedArticleId\x12#\n" +
	"\rrelation_type\x18\x03 \x01(\tR\frelationType\x12)\n" +
	"\x10similarity_score\x18\x04 \x01(\x01R\x0fsimilarityScore\"\x92\x05\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\afeed_id\x18\x02 \x01(\tR\x06feedId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04link\x18\x05 \x01(\tR\x04link\x12=\n" +
	"\fpublished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x129\n" +
	"\n" +
	"fetched_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tfetchedAt\x12\x17\n" +
	"\x04read\x18\b \x01(\bH\x00R\x04read\x88\x01\x01\x12!\n" +
	"\x04tags\x18\t \x03(\v2\r.downlink.TagR\x04tags\x12(\n" +
	"\rcategory_name\x18\n" +
	" \x01(\tH\x01R\fcategoryName\x88\x01\x01\x12.\n" +
	"\bcategory\x18\v \x01(\v2\x12.downlink.CategoryR\bcategory\x12\x1d\n" +
	"\n" +
	"hero_image\x18\f \x01(\tR\theroImage\x12#\n" +
	"\n" +
	"bookmarked\x18\r \x01(\bH\x02R\n" +
	"bookmarked\x88\x01\x01\x12C\n" +
	"\x10related_articles\x18\x0e \x03(\v2\x18.downlink.RelatedArticleR\x0frelatedArticles\x12;\n" +
	"\x17latest_importance_score\x18\x0f \x01(\x05H\x03R\x15latestImportanceScore\x88\x01\x01B\a\n" +
	"\x05_readB\x10\n" +
	"\x0e_category_nameB\r\n" +
	"\v_bookmarkedB\x1a\n" +
	"\x18_latest_importance_score\"\xb2\x02\n" +
	"\rArticleUpdate\x12\x17\n" +
	"\x04read\x18\x01 \x01(\bH\x00R\x04read\x88\x01\x01\x12\x17\n" +
	"\atag_ids\x18\x02 \x03(\tR\x06tagIds\x12(\n" +
	"\rcategory_name\x18\x03 \x01(\tH\x01R\fcategoryName\x88\x01\x01\x12\"\n" +
	"\n" +
	"hero_image\x18\x04 \x01(\tH\x02R\theroImage\x88\x01\x01\x12#\n" +
	"\n" +
	"bookmarked\x18\x05 \x01(\bH\x03R\n" +
	"bookmarked\x88\x01\x01\x12C\n" +
	"\x10related_articles\x18\x06 \x03(\v2\x18.downlink.RelatedArticleR\x0frelatedArticlesB\a\n" +
	"\x05_readB\x10\n" +
	"\x0e_category_nameB\r\n" +
	"\v_hero_imageB\r\n" +
	"\v_bookmarked\"\xb3\x03\n" +
	"\rArticleFilter\x12\x1f\n" +
	"\vunread_only\x18\x01 \x01(\bR\n" +
	"unreadOnly\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12\x15\n" +
	"\x06tag_id\x18\x03 \x01(\tR\x05tagId\x12'\n" +
	"\x0fbookmarked_only\x18\x04 \x01(\bR\x0ebookmarkedOnly\x12\"\n" +
	"\rrelated_to_id\x18\x05 \x01(\tR\vrelatedToId\x129\n" +
	"\n" +
	"start_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x17\n" +
	"\afeed_id\x18\b \x01(\tR\x06feedId\x12\x16\n" +
	"\x06offset\x18\t \x01(\rR\x06offset\x12)\n" +
	"\x10exclude_digested\x18\n" +
	" \x01(\bR\x0fexcludeDigested\x12\x14\n" +
	"\x05limit\x18\v \x01(\rR\x05limit\x12\x14\n" +
	"\x05query\x18\f \x01(\tR\x05query\"E\n" +
	"\x14ListArticlesResponse\x12-\n" +
	"\barticles\x18\x01 \x03(\v2\x11.downlink.ArticleR\barticles\"\x86\x02\n" +
	"\x15ArticleCountsResponse\x12(\n" +
	"\x10all_unread_count\x18\x01 \x01(\x05R\x0eallUnreadCount\x12)\n" +
	"\x10bookmarked_count\x18\x02 \x01(\x05R\x0fbookmarkedCount\x12W\n" +
	"\x0eunread_by_feed\x18\x03 \x03(\v21.downlink.ArticleCountsResponse.UnreadByFeedEntryR\funreadByFeed\x1a?\n" +
	"\x11UnreadByFeedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"#\n" +
	"\x11GetArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"W\n" +
	"\x14UpdateArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x06update\x18\x02 \x01(\v2\x17.downlink.ArticleUpdateR\x06update\".\n" +
	"\x13MarkFeedReadRequest\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\tR\x06feedId\"0\n" +
	"\x1aGetOrCreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"M\n" +
	"\x1bGetOrCreateCategoryResponse\x12.\n" +
	"\bcategory\x18\x01 \x01(\v2\x12.downlink.CategoryR\bcategory2y\n" +
	"\x11CategoriesService\x12d\n" +
	"\x13GetOrCreateCategory\x12$.downlink.GetOrCreateCategoryRequest\x1a%.downlink.GetOrCreateCategoryResponse\"\x002\x87\x03\n" +
	"\x0eArticleService\x12I\n" +
	"\fListArticles\x12\x17.downlink.ArticleFilter\x1a\x1e.downlink.ListArticlesResponse\"\x00\x12N\n" +
	"\x10GetArticleCounts\x12\x17.downlink.ArticleFilter\x1a\x1f.downlink.ArticleCountsResponse\"\x00\x12>\n" +
	"\n" +
	"GetArticle\x12\x1b.downlink.GetArticleRequest\x1a\x11.downlink.Article\"\x00\x12I\n" +
	"\rUpdateArticle\x12\x1e.downlink.UpdateArticleRequest\x1a\x16.google.protobuf.Empty\"\x00\x12O\n" +
	"\x14MarkFeedArticlesRead\x12\x1d.downlink.MarkFeedReadRequest\x1a\x16.google.protobuf.Empty\"\x00B\tZ\aprotos/b\x06proto3"

var (
	file_articles_proto_rawDescOnce sync.Once
	file_articles_proto_rawDescData []byte
)

func file_articles_proto_rawDescGZIP() []byte {
	file_articles_proto_rawDescOnce.Do(func() {
		file_articles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_articles_proto_rawDesc), len(file_articles_proto_rawDesc)))
	})
	return file_articles_proto_rawDescData
}

var file_articles_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_articles_proto_goTypes = []any{
	(*Category)(nil),                    // 0: downlink.Category
	(*Tag)(nil),                         // 1: downlink.Tag
	(*RelatedArticle)(nil),              // 2: downlink.RelatedArticle
	(*Article)(nil),                     // 3: downlink.Article
	(*ArticleUpdate)(nil),               // 4: downlink.ArticleUpdate
	(*ArticleFilter)(nil),               // 5: downlink.ArticleFilter
	(*ListArticlesResponse)(nil),        // 6: downlink.ListArticlesResponse
	(*ArticleCountsResponse)(nil),       // 7: downlink.ArticleCountsResponse
	(*GetArticleRequest)(nil),           // 8: downlink.GetArticleRequest
	(*UpdateArticleRequest)(nil),        // 9: downlink.UpdateArticleRequest
	(*MarkFeedReadRequest)(nil),         // 10: downlink.MarkFeedReadRequest
	(*GetOrCreateCategoryRequest)(nil),  // 11: downlink.GetOrCreateCategoryRequest
	(*GetOrCreateCategoryResponse)(nil), // 12: downlink.GetOrCreateCategoryResponse
	nil,                                 // 13: downlink.ArticleCountsResponse.UnreadByFeedEntry
	(*timestamppb.Timestamp)(nil),       // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 15: google.protobuf.Empty
}
var file_articles_proto_depIdxs = []int32{
	3,  // 0: downlink.Category.articles:type_name -> downlink.Article
	3,  // 1: downlink.Tag.articles:type_name -> downlink.Article
	14, // 2: downlink.Article.published_at:type_name -> google.protobuf.Timestamp
	14, // 3: downlink.Article.fetched_at:type_name -> google.protobuf.Timestamp
	1,  // 4: downlink.Article.tags:type_name -> downlink.Tag
	0,  // 5: downlink.Article.category:type_name -> downlink.Category
	2,  // 6: downlink.Article.related_articles:type_name -> downlink.RelatedArticle
	2,  // 7: downlink.ArticleUpdate.related_articles:type_name -> downlink.RelatedArticle
	14, // 8: downlink.ArticleFilter.start_date:type_name -> google.protobuf.Timestamp
	14, // 9: downlink.ArticleFilter.end_date:type_name -> google.protobuf.Timestamp
	3,  // 10: downlink.ListArticlesResponse.articles:type_name -> downlink.Article
	13, // 11: downlink.ArticleCountsResponse.unread_by_feed:type_name -> downlink.ArticleCountsResponse.UnreadByFeedEntry
	4,  // 12: downlink.UpdateArticleRequest.update:type_name -> downlink.ArticleUpdate
	0,  // 13: downlink.GetOrCreateCategoryResponse.category:type_name -> downlink.Category
	11, // 14: downlink.CategoriesService.GetOrCreateCategory:input_type -> downlink.GetOrCreateCategoryRequest
	5,  // 15: downlink.ArticleService.ListArticles:input_type -> downlink.ArticleFilter
	5,  // 16: downlink.ArticleService.GetArticleCounts:input_type -> downlink.ArticleFilter
	8,  // 17: downlink.ArticleService.GetArticle:input_type -> downlink.GetArticleRequest
	9,  // 18: downlink.ArticleService.UpdateArticle:input_type -> downlink.UpdateArticleRequest
	10, // 19: downlink.ArticleService.MarkFeedArticlesRead:input_type -> downlink.MarkFeedReadRequest
	12, // 20: downlink.CategoriesService.GetOrCreateCategory:output_type -> downlink.GetOrCreateCategoryResponse
	6,  // 21: downlink.ArticleService.ListArticles:output_type -> downlink.ListArticlesResponse
	7,  // 22: downlink.ArticleService.GetArticleCounts:output_type -> downlink.ArticleCountsResponse
	3,  // 23: downlink.ArticleService.GetArticle:output_type -> downlink.Article
	15, // 24: downlink.ArticleService.UpdateArticle:output_type -> google.protobuf.Empty
	15, // 25: downlink.ArticleService.MarkFeedArticlesRead:output_type -> google.protobuf.Empty
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_articles_proto_init() }
func file_articles_proto_init() {
	if File_articles_proto != nil {
		return
	}
	file_articles_proto_msgTypes[3].OneofWrappers = []any{}
	file_articles_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_articles_proto_rawDesc), len(file_articles_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_articles_proto_goTypes,
		DependencyIndexes: file_articles_proto_depIdxs,
		MessageInfos:      file_articles_proto_msgTypes,
	}.Build()
	File_articles_proto = out.File
	file_articles_proto_goTypes = nil
	file_articles_proto_depIdxs = nil
}
