// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: auth.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_StartCodexLogin_FullMethodName            = "/downlink.AuthService/StartCodexLogin"
	AuthService_PollCodexLogin_FullMethodName             = "/downlink.AuthService/PollCodexLogin"
	AuthService_ListCodexCredentials_FullMethodName       = "/downlink.AuthService/ListCodexCredentials"
	AuthService_RemoveCodexCredential_FullMethodName      = "/downlink.AuthService/RemoveCodexCredential"
	AuthService_SetCodexCredentialPriority_FullMethodName = "/downlink.AuthService/SetCodexCredentialPriority"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthService manages Codex/ChatGPT OAuth credentials.
type AuthServiceClient interface {
	// StartCodexLogin begins a device-code login flow for openai-codex.
	StartCodexLogin(ctx context.Context, in *StartCodexLoginRequest, opts ...grpc.CallOption) (*StartCodexLoginResponse, error)
	// PollCodexLogin polls the status of an in-progress login session.
	PollCodexLogin(ctx context.Context, in *PollCodexLoginRequest, opts ...grpc.CallOption) (*PollCodexLoginResponse, error)
	// ListCodexCredentials lists all registered credentials for a provider.
	ListCodexCredentials(ctx context.Context, in *ListCodexCredentialsRequest, opts ...grpc.CallOption) (*ListCodexCredentialsResponse, error)
	// RemoveCodexCredential removes a credential by ID.
	RemoveCodexCredential(ctx context.Context, in *RemoveCodexCredentialRequest, opts ...grpc.CallOption) (*RemoveCodexCredentialResponse, error)
	// SetCodexCredentialPriority updates the priority of a credential.
	SetCodexCredentialPriority(ctx context.Context, in *SetCodexCredentialPriorityRequest, opts ...grpc.CallOption) (*SetCodexCredentialPriorityResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) StartCodexLogin(ctx context.Context, in *StartCodexLoginRequest, opts ...grpc.CallOption) (*StartCodexLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartCodexLoginResponse)
	err := c.cc.Invoke(ctx, AuthService_StartCodexLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) PollCodexLogin(ctx context.Context, in *PollCodexLoginRequest, opts ...grpc.CallOption) (*PollCodexLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollCodexLoginResponse)
	err := c.cc.Invoke(ctx, AuthService_PollCodexLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ListCodexCredentials(ctx context.Context, in *ListCodexCredentialsRequest, opts ...grpc.CallOption) (*ListCodexCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCodexCredentialsResponse)
	err := c.cc.Invoke(ctx, AuthService_ListCodexCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RemoveCodexCredential(ctx context.Context, in *RemoveCodexCredentialRequest, opts ...grpc.CallOption) (*RemoveCodexCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveCodexCredentialResponse)
	err := c.cc.Invoke(ctx, AuthService_RemoveCodexCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SetCodexCredentialPriority(ctx context.Context, in *SetCodexCredentialPriorityRequest, opts ...grpc.CallOption) (*SetCodexCredentialPriorityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCodexCredentialPriorityResponse)
	err := c.cc.Invoke(ctx, AuthService_SetCodexCredentialPriority_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// AuthService manages Codex/ChatGPT OAuth credentials.
type AuthServiceServer interface {
	// StartCodexLogin begins a device-code login flow for openai-codex.
	StartCodexLogin(context.Context, *StartCodexLoginRequest) (*StartCodexLoginResponse, error)
	// PollCodexLogin polls the status of an in-progress login session.
	PollCodexLogin(context.Context, *PollCodexLoginRequest) (*PollCodexLoginResponse, error)
	// ListCodexCredentials lists all registered credentials for a provider.
	ListCodexCredentials(context.Context, *ListCodexCredentialsRequest) (*ListCodexCredentialsResponse, error)
	// RemoveCodexCredential removes a credential by ID.
	RemoveCodexCredential(context.Context, *RemoveCodexCredentialRequest) (*RemoveCodexCredentialResponse, error)
	// SetCodexCredentialPriority updates the priority of a credential.
	SetCodexCredentialPriority(context.Context, *SetCodexCredentialPriorityRequest) (*SetCodexCredentialPriorityResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) StartCodexLogin(context.Context, *StartCodexLoginRequest) (*StartCodexLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartCodexLogin not implemented")
}
func (UnimplementedAuthServiceServer) PollCodexLogin(context.Context, *PollCodexLoginRequest) (*PollCodexLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PollCodexLogin not implemented")
}
func (UnimplementedAuthServiceServer) ListCodexCredentials(context.Context, *ListCodexCredentialsRequest) (*ListCodexCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCodexCredentials not implemented")
}
func (UnimplementedAuthServiceServer) RemoveCodexCredential(context.Context, *RemoveCodexCredentialRequest) (*RemoveCodexCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCodexCredential not implemented")
}
func (UnimplementedAuthServiceServer) SetCodexCredentialPriority(context.Context, *SetCodexCredentialPriorityRequest) (*SetCodexCredentialPriorityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCodexCredentialPriority not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_StartCodexLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCodexLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).StartCodexLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_StartCodexLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).StartCodexLogin(ctx, req.(*StartCodexLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_PollCodexLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollCodexLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).PollCodexLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_PollCodexLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).PollCodexLogin(ctx, req.(*PollCodexLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ListCodexCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCodexCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ListCodexCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ListCodexCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ListCodexCredentials(ctx, req.(*ListCodexCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RemoveCodexCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCodexCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RemoveCodexCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RemoveCodexCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RemoveCodexCredential(ctx, req.(*RemoveCodexCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SetCodexCredentialPriority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCodexCredentialPriorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SetCodexCredentialPriority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SetCodexCredentialPriority_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SetCodexCredentialPriority(ctx, req.(*SetCodexCredentialPriorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "downlink.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartCodexLogin",
			Handler:    _AuthService_StartCodexLogin_Handler,
		},
		{
			MethodName: "PollCodexLogin",
			Handler:    _AuthService_PollCodexLogin_Handler,
		},
		{
			MethodName: "ListCodexCredentials",
			Handler:    _AuthService_ListCodexCredentials_Handler,
		},
		{
			MethodName: "RemoveCodexCredential",
			Handler:    _AuthService_RemoveCodexCredential_Handler,
		},
		{
			MethodName: "SetCodexCredentialPriority",
			Handler:    _AuthService_SetCodexCredentialPriority_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
