// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: auth.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartCodexLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// provider_name is the name of the openai-codex provider config entry.
	// If it doesn't exist in config.json, it will be created.
	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	// model_name is only used when auto-creating the provider entry.
	ModelName     string `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCodexLoginRequest) Reset() {
	*x = StartCodexLoginRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCodexLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCodexLoginRequest) ProtoMessage() {}

func (x *StartCodexLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCodexLoginRequest.ProtoReflect.Descriptor instead.
func (*StartCodexLoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *StartCodexLoginRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *StartCodexLoginRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type StartCodexLoginResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserCode        string                 `protobuf:"bytes,2,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	VerificationUrl string                 `protobuf:"bytes,3,opt,name=verification_url,json=verificationUrl,proto3" json:"verification_url,omitempty"`
	ExpiresIn       int32                  `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	PollInterval    int32                  `protobuf:"varint,5,opt,name=poll_interval,json=pollInterval,proto3" json:"poll_interval,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartCodexLoginResponse) Reset() {
	*x = StartCodexLoginResponse{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCodexLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCodexLoginResponse) ProtoMessage() {}

func (x *StartCodexLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCodexLoginResponse.ProtoReflect.Descriptor instead.
func (*StartCodexLoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *StartCodexLoginResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartCodexLoginResponse) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *StartCodexLoginResponse) GetVerificationUrl() string {
	if x != nil {
		return x.VerificationUrl
	}
	return ""
}

func (x *StartCodexLoginResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *StartCodexLoginResponse) GetPollInterval() int32 {
	if x != nil {
		return x.PollInterval
	}
	return 0
}

type PollCodexLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollCodexLoginRequest) Reset() {
	*x = PollCodexLoginRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollCodexLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollCodexLoginRequest) ProtoMessage() {}

func (x *PollCodexLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollCodexLoginRequest.ProtoReflect.Descriptor instead.
func (*PollCodexLoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *PollCodexLoginRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PollCodexLoginResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// status is one of: "pending", "approved", "expired", "error"
	Status       string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// credential_id is set when status == "approved"
	CredentialId  string `protobuf:"bytes,4,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	Label         string `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollCodexLoginResponse) Reset() {
	*x = PollCodexLoginResponse{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollCodexLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollCodexLoginResponse) ProtoMessage() {}

func (x *PollCodexLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollCodexLoginResponse.ProtoReflect.Descriptor instead.
func (*PollCodexLoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *PollCodexLoginResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PollCodexLoginResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PollCodexLoginResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PollCodexLoginResponse) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *PollCodexLoginResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type ListCodexCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCodexCredentialsRequest) Reset() {
	*x = ListCodexCredentialsRequest{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCodexCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCodexCredentialsRequest) ProtoMessage() {}

func (x *ListCodexCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCodexCredentialsRequest.ProtoReflect.Descriptor instead.
func (*ListCodexCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ListCodexCredentialsRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

type CodexCredentialInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label           string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Priority        int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	LastStatus      string                 `protobuf:"bytes,4,opt,name=last_status,json=lastStatus,proto3" json:"last_status,omitempty"`
	LastErrorReason string                 `protobuf:"bytes,5,opt,name=last_error_reason,json=lastErrorReason,proto3" json:"last_error_reason,omitempty"`
	AuthMode        string                 `protobuf:"bytes,6,opt,name=auth_mode,json=authMode,proto3" json:"auth_mode,omitempty"`
	Source          string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CodexCredentialInfo) Reset() {
	*x = CodexCredentialInfo{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodexCredentialInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodexCredentialInfo) ProtoMessage() {}

func (x *CodexCredentialInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodexCredentialInfo.ProtoReflect.Descriptor instead.
func (*CodexCredentialInfo) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *CodexCredentialInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CodexCredentialInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CodexCredentialInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CodexCredentialInfo) GetLastStatus() string {
	if x != nil {
		return x.LastStatus
	}
	return ""
}

func (x *CodexCredentialInfo) GetLastErrorReason() string {
	if x != nil {
		return x.LastErrorReason
	}
	return ""
}

func (x *CodexCredentialInfo) GetAuthMode() string {
	if x != nil {
		return x.AuthMode
	}
	return ""
}

func (x *CodexCredentialInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ListCodexCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []*CodexCredentialInfo `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCodexCredentialsResponse) Reset() {
	*x = ListCodexCredentialsResponse{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCodexCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCodexCredentialsResponse) ProtoMessage() {}

func (x *ListCodexCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCodexCredentialsResponse.ProtoReflect.Descriptor instead.
func (*ListCodexCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ListCodexCredentialsResponse) GetCredentials() []*CodexCredentialInfo {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type RemoveCodexCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	CredentialId  string                 `protobuf:"bytes,2,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCodexCredentialRequest) Reset() {
	*x = RemoveCodexCredentialRequest{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCodexCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCodexCredentialRequest) ProtoMessage() {}

func (x *RemoveCodexCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCodexCredentialRequest.ProtoReflect.Descriptor instead.
func (*RemoveCodexCredentialRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveCodexCredentialRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *RemoveCodexCredentialRequest) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

type RemoveCodexCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCodexCredentialResponse) Reset() {
	*x = RemoveCodexCredentialResponse{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCodexCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCodexCredentialResponse) ProtoMessage() {}

func (x *RemoveCodexCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCodexCredentialResponse.ProtoReflect.Descriptor instead.
func (*RemoveCodexCredentialResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveCodexCredentialResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type SetCodexCredentialPriorityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	CredentialId  string                 `protobuf:"bytes,2,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCodexCredentialPriorityRequest) Reset() {
	*x = SetCodexCredentialPriorityRequest{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCodexCredentialPriorityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCodexCredentialPriorityRequest) ProtoMessage() {}

func (x *SetCodexCredentialPriorityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCodexCredentialPriorityRequest.ProtoReflect.Descriptor instead.
func (*SetCodexCredentialPriorityRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *SetCodexCredentialPriorityRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *SetCodexCredentialPriorityRequest) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *SetCodexCredentialPriorityRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type SetCodexCredentialPriorityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCodexCredentialPriorityResponse) Reset() {
	*x = SetCodexCredentialPriorityResponse{}
	mi := &file_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCodexCredentialPriorityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCodexCredentialPriorityResponse) ProtoMessage() {}

func (x *SetCodexCredentialPriorityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCodexCredentialPriorityResponse.ProtoReflect.Descriptor instead.
func (*SetCodexCredentialPriorityResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{10}
}

func (x *SetCodexCredentialPriorityResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\bdownlink\"\\\n" +
	"\x16StartCodexLoginRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\"\xc4\x01\n" +
	"\x17StartCodexLoginResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tuser_code\x18\x02 \x01(\tR\buserCode\x12)\n" +
	"\x10verification_url\x18\x03 \x01(\tR\x0fverificationUrl\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x05R\texpiresIn\x12#\n" +
	"\rpoll_interval\x18\x05 \x01(\x05R\fpollInterval\"6\n" +
	"\x15PollCodexLoginRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xaf\x01\n" +
	"\x16PollCodexLoginResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12#\n" +
	"\rcredential_id\x18\x04 \x01(\tR\fcredentialId\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\"B\n" +
	"\x1bListCodexCredentialsRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\"\xd9\x01\n" +
	"\x13CodexCredentialInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vlast_status\x18\x04 \x01(\tR\n" +
	"lastStatus\x12*\n" +
	"\x11last_error_reason\x18\x05 \x01(\tR\x0flastErrorReason\x12\x1b\n" +
	"\tauth_mode\x18\x06 \x01(\tR\bauthMode\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\"_\n" +
	"\x1cListCodexCredentialsResponse\x12?\n" +
	"\vcredentials\x18\x01 \x03(\v2\x1d.downlink.CodexCredentialInfoR\vcredentials\"h\n" +
	"\x1cRemoveCodexCredentialRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12#\n" +
	"\rcredential_id\x18\x02 \x01(\tR\fcredentialId\"9\n" +
	"\x1dRemoveCodexCredentialResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\"\x89\x01\n" +
	"!SetCodexCredentialPriorityRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12#\n" +
	"\rcredential_id\x18\x02 \x01(\tR\fcredentialId\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\">\n" +
	"\"SetCodexCredentialPriorityResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated2\x8e\x04\n" +
	"\vAuthService\x12X\n" +
	"\x0fStartCodexLogin\x12 .downlink.StartCodexLoginRequest\x1a!.downlink.StartCodexLoginResponse\"\x00\x12U\n" +
	"\x0ePollCodexLogin\x12\x1f.downlink.PollCodexLoginRequest\x1a .downlink.PollCodexLoginResponse\"\x00\x12g\n" +
	"\x14ListCodexCredentials\x12%.downlink.ListCodexCredentialsRequest\x1a&.downlink.ListCodexCredentialsResponse\"\x00\x12j\n" +
	"\x15RemoveCodexCredential\x12&.downlink.RemoveCodexCredentialRequest\x1a'.downlink.RemoveCodexCredentialResponse\"\x00\x12y\n" +
	"\x1aSetCodexCredentialPriority\x12+.downlink.SetCodexCredentialPriorityRequest\x1a,.downlink.SetCodexCredentialPriorityResponse\"\x00B\tZ\aprotos/b\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_auth_proto_goTypes = []any{
	(*StartCodexLoginRequest)(nil),             // 0: downlink.StartCodexLoginRequest
	(*StartCodexLoginResponse)(nil),            // 1: downlink.StartCodexLoginResponse
	(*PollCodexLoginRequest)(nil),              // 2: downlink.PollCodexLoginRequest
	(*PollCodexLoginResponse)(nil),             // 3: downlink.PollCodexLoginResponse
	(*ListCodexCredentialsRequest)(nil),        // 4: downlink.ListCodexCredentialsRequest
	(*CodexCredentialInfo)(nil),                // 5: downlink.CodexCredentialInfo
	(*ListCodexCredentialsResponse)(nil),       // 6: downlink.ListCodexCredentialsResponse
	(*RemoveCodexCredentialRequest)(nil),       // 7: downlink.RemoveCodexCredentialRequest
	(*RemoveCodexCredentialResponse)(nil),      // 8: downlink.RemoveCodexCredentialResponse
	(*SetCodexCredentialPriorityRequest)(nil),  // 9: downlink.SetCodexCredentialPriorityRequest
	(*SetCodexCredentialPriorityResponse)(nil), // 10: downlink.SetCodexCredentialPriorityResponse
}
var file_auth_proto_depIdxs = []int32{
	5,  // 0: downlink.ListCodexCredentialsResponse.credentials:type_name -> downlink.CodexCredentialInfo
	0,  // 1: downlink.AuthService.StartCodexLogin:input_type -> downlink.StartCodexLoginRequest
	2,  // 2: downlink.AuthService.PollCodexLogin:input_type -> downlink.PollCodexLoginRequest
	4,  // 3: downlink.AuthService.ListCodexCredentials:input_type -> downlink.ListCodexCredentialsRequest
	7,  // 4: downlink.AuthService.RemoveCodexCredential:input_type -> downlink.RemoveCodexCredentialRequest
	9,  // 5: downlink.AuthService.SetCodexCredentialPriority:input_type -> downlink.SetCodexCredentialPriorityRequest
	1,  // 6: downlink.AuthService.StartCodexLogin:output_type -> downlink.StartCodexLoginResponse
	3,  // 7: downlink.AuthService.PollCodexLogin:output_type -> downlink.PollCodexLoginResponse
	6,  // 8: downlink.AuthService.ListCodexCredentials:output_type -> downlink.ListCodexCredentialsResponse
	8,  // 9: downlink.AuthService.RemoveCodexCredential:output_type -> downlink.RemoveCodexCredentialResponse
	10, // 10: downlink.AuthService.SetCodexCredentialPriority:output_type -> downlink.SetCodexCredentialPriorityResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
