// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: creds.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CredsService_StartCodexLogin_FullMethodName            = "/downlink.CredsService/StartCodexLogin"
	CredsService_PollCodexLogin_FullMethodName             = "/downlink.CredsService/PollCodexLogin"
	CredsService_ListCodexCredentials_FullMethodName       = "/downlink.CredsService/ListCodexCredentials"
	CredsService_RemoveCodexCredential_FullMethodName      = "/downlink.CredsService/RemoveCodexCredential"
	CredsService_SetCodexCredentialPriority_FullMethodName = "/downlink.CredsService/SetCodexCredentialPriority"
	CredsService_StartClaudeLogin_FullMethodName           = "/downlink.CredsService/StartClaudeLogin"
	CredsService_CompleteClaudeLogin_FullMethodName        = "/downlink.CredsService/CompleteClaudeLogin"
)

// CredsServiceClient is the client API for CredsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CredsService manages Codex/ChatGPT OAuth credentials.
type CredsServiceClient interface {
	// StartCodexLogin begins a device-code login flow for openai-codex.
	StartCodexLogin(ctx context.Context, in *StartCodexLoginRequest, opts ...grpc.CallOption) (*StartCodexLoginResponse, error)
	// PollCodexLogin polls the status of an in-progress login session.
	PollCodexLogin(ctx context.Context, in *PollCodexLoginRequest, opts ...grpc.CallOption) (*PollCodexLoginResponse, error)
	// ListCodexCredentials lists all registered credentials for a provider.
	ListCodexCredentials(ctx context.Context, in *ListCodexCredentialsRequest, opts ...grpc.CallOption) (*ListCodexCredentialsResponse, error)
	// RemoveCodexCredential removes a credential by ID.
	RemoveCodexCredential(ctx context.Context, in *RemoveCodexCredentialRequest, opts ...grpc.CallOption) (*RemoveCodexCredentialResponse, error)
	// SetCodexCredentialPriority updates the priority of a credential.
	SetCodexCredentialPriority(ctx context.Context, in *SetCodexCredentialPriorityRequest, opts ...grpc.CallOption) (*SetCodexCredentialPriorityResponse, error)
	// StartClaudeLogin begins a PKCE authorization-code login flow for claude-code.
	// Returns the browser URL the user must open; the server holds the PKCE
	// verifier and state for the session.
	StartClaudeLogin(ctx context.Context, in *StartClaudeLoginRequest, opts ...grpc.CallOption) (*StartClaudeLoginResponse, error)
	// CompleteClaudeLogin finishes the flow with the "<code>#<state>" string the
	// user pastes back, exchanging it for tokens and storing the credential.
	CompleteClaudeLogin(ctx context.Context, in *CompleteClaudeLoginRequest, opts ...grpc.CallOption) (*CompleteClaudeLoginResponse, error)
}

type credsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCredsServiceClient(cc grpc.ClientConnInterface) CredsServiceClient {
	return &credsServiceClient{cc}
}

func (c *credsServiceClient) StartCodexLogin(ctx context.Context, in *StartCodexLoginRequest, opts ...grpc.CallOption) (*StartCodexLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartCodexLoginResponse)
	err := c.cc.Invoke(ctx, CredsService_StartCodexLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credsServiceClient) PollCodexLogin(ctx context.Context, in *PollCodexLoginRequest, opts ...grpc.CallOption) (*PollCodexLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollCodexLoginResponse)
	err := c.cc.Invoke(ctx, CredsService_PollCodexLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credsServiceClient) ListCodexCredentials(ctx context.Context, in *ListCodexCredentialsRequest, opts ...grpc.CallOption) (*ListCodexCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCodexCredentialsResponse)
	err := c.cc.Invoke(ctx, CredsService_ListCodexCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credsServiceClient) RemoveCodexCredential(ctx context.Context, in *RemoveCodexCredentialRequest, opts ...grpc.CallOption) (*RemoveCodexCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveCodexCredentialResponse)
	err := c.cc.Invoke(ctx, CredsService_RemoveCodexCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credsServiceClient) SetCodexCredentialPriority(ctx context.Context, in *SetCodexCredentialPriorityRequest, opts ...grpc.CallOption) (*SetCodexCredentialPriorityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCodexCredentialPriorityResponse)
	err := c.cc.Invoke(ctx, CredsService_SetCodexCredentialPriority_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credsServiceClient) StartClaudeLogin(ctx context.Context, in *StartClaudeLoginRequest, opts ...grpc.CallOption) (*StartClaudeLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartClaudeLoginResponse)
	err := c.cc.Invoke(ctx, CredsService_StartClaudeLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credsServiceClient) CompleteClaudeLogin(ctx context.Context, in *CompleteClaudeLoginRequest, opts ...grpc.CallOption) (*CompleteClaudeLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteClaudeLoginResponse)
	err := c.cc.Invoke(ctx, CredsService_CompleteClaudeLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CredsServiceServer is the server API for CredsService service.
// All implementations must embed UnimplementedCredsServiceServer
// for forward compatibility.
//
// CredsService manages Codex/ChatGPT OAuth credentials.
type CredsServiceServer interface {
	// StartCodexLogin begins a device-code login flow for openai-codex.
	StartCodexLogin(context.Context, *StartCodexLoginRequest) (*StartCodexLoginResponse, error)
	// PollCodexLogin polls the status of an in-progress login session.
	PollCodexLogin(context.Context, *PollCodexLoginRequest) (*PollCodexLoginResponse, error)
	// ListCodexCredentials lists all registered credentials for a provider.
	ListCodexCredentials(context.Context, *ListCodexCredentialsRequest) (*ListCodexCredentialsResponse, error)
	// RemoveCodexCredential removes a credential by ID.
	RemoveCodexCredential(context.Context, *RemoveCodexCredentialRequest) (*RemoveCodexCredentialResponse, error)
	// SetCodexCredentialPriority updates the priority of a credential.
	SetCodexCredentialPriority(context.Context, *SetCodexCredentialPriorityRequest) (*SetCodexCredentialPriorityResponse, error)
	// StartClaudeLogin begins a PKCE authorization-code login flow for claude-code.
	// Returns the browser URL the user must open; the server holds the PKCE
	// verifier and state for the session.
	StartClaudeLogin(context.Context, *StartClaudeLoginRequest) (*StartClaudeLoginResponse, error)
	// CompleteClaudeLogin finishes the flow with the "<code>#<state>" string the
	// user pastes back, exchanging it for tokens and storing the credential.
	CompleteClaudeLogin(context.Context, *CompleteClaudeLoginRequest) (*CompleteClaudeLoginResponse, error)
	mustEmbedUnimplementedCredsServiceServer()
}

// UnimplementedCredsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCredsServiceServer struct{}

func (UnimplementedCredsServiceServer) StartCodexLogin(context.Context, *StartCodexLoginRequest) (*StartCodexLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartCodexLogin not implemented")
}
func (UnimplementedCredsServiceServer) PollCodexLogin(context.Context, *PollCodexLoginRequest) (*PollCodexLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollCodexLogin not implemented")
}
func (UnimplementedCredsServiceServer) ListCodexCredentials(context.Context, *ListCodexCredentialsRequest) (*ListCodexCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCodexCredentials not implemented")
}
func (UnimplementedCredsServiceServer) RemoveCodexCredential(context.Context, *RemoveCodexCredentialRequest) (*RemoveCodexCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveCodexCredential not implemented")
}
func (UnimplementedCredsServiceServer) SetCodexCredentialPriority(context.Context, *SetCodexCredentialPriorityRequest) (*SetCodexCredentialPriorityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCodexCredentialPriority not implemented")
}
func (UnimplementedCredsServiceServer) StartClaudeLogin(context.Context, *StartClaudeLoginRequest) (*StartClaudeLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartClaudeLogin not implemented")
}
func (UnimplementedCredsServiceServer) CompleteClaudeLogin(context.Context, *CompleteClaudeLoginRequest) (*CompleteClaudeLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteClaudeLogin not implemented")
}
func (UnimplementedCredsServiceServer) mustEmbedUnimplementedCredsServiceServer() {}
func (UnimplementedCredsServiceServer) testEmbeddedByValue()                      {}

// UnsafeCredsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CredsServiceServer will
// result in compilation errors.
type UnsafeCredsServiceServer interface {
	mustEmbedUnimplementedCredsServiceServer()
}

func RegisterCredsServiceServer(s grpc.ServiceRegistrar, srv CredsServiceServer) {
	// If the following call panics, it indicates UnimplementedCredsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CredsService_ServiceDesc, srv)
}

func _CredsService_StartCodexLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCodexLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredsServiceServer).StartCodexLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredsService_StartCodexLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredsServiceServer).StartCodexLogin(ctx, req.(*StartCodexLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredsService_PollCodexLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollCodexLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredsServiceServer).PollCodexLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredsService_PollCodexLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredsServiceServer).PollCodexLogin(ctx, req.(*PollCodexLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredsService_ListCodexCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCodexCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredsServiceServer).ListCodexCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredsService_ListCodexCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredsServiceServer).ListCodexCredentials(ctx, req.(*ListCodexCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredsService_RemoveCodexCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCodexCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredsServiceServer).RemoveCodexCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredsService_RemoveCodexCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredsServiceServer).RemoveCodexCredential(ctx, req.(*RemoveCodexCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredsService_SetCodexCredentialPriority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCodexCredentialPriorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredsServiceServer).SetCodexCredentialPriority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredsService_SetCodexCredentialPriority_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredsServiceServer).SetCodexCredentialPriority(ctx, req.(*SetCodexCredentialPriorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredsService_StartClaudeLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartClaudeLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredsServiceServer).StartClaudeLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredsService_StartClaudeLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredsServiceServer).StartClaudeLogin(ctx, req.(*StartClaudeLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredsService_CompleteClaudeLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteClaudeLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredsServiceServer).CompleteClaudeLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredsService_CompleteClaudeLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredsServiceServer).CompleteClaudeLogin(ctx, req.(*CompleteClaudeLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CredsService_ServiceDesc is the grpc.ServiceDesc for CredsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CredsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "downlink.CredsService",
	HandlerType: (*CredsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartCodexLogin",
			Handler:    _CredsService_StartCodexLogin_Handler,
		},
		{
			MethodName: "PollCodexLogin",
			Handler:    _CredsService_PollCodexLogin_Handler,
		},
		{
			MethodName: "ListCodexCredentials",
			Handler:    _CredsService_ListCodexCredentials_Handler,
		},
		{
			MethodName: "RemoveCodexCredential",
			Handler:    _CredsService_RemoveCodexCredential_Handler,
		},
		{
			MethodName: "SetCodexCredentialPriority",
			Handler:    _CredsService_SetCodexCredentialPriority_Handler,
		},
		{
			MethodName: "StartClaudeLogin",
			Handler:    _CredsService_StartClaudeLogin_Handler,
		},
		{
			MethodName: "CompleteClaudeLogin",
			Handler:    _CredsService_CompleteClaudeLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "creds.proto",
}
