// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: digests.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DigestService_ListDigests_FullMethodName       = "/downlink.DigestService/ListDigests"
	DigestService_GetDigest_FullMethodName         = "/downlink.DigestService/GetDigest"
	DigestService_GetDigestArticles_FullMethodName = "/downlink.DigestService/GetDigestArticles"
	DigestService_GenerateDigest_FullMethodName    = "/downlink.DigestService/GenerateDigest"
)

// DigestServiceClient is the client API for DigestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DigestService provides methods for working with digests
type DigestServiceClient interface {
	// ListDigests retrieves all digests
	ListDigests(ctx context.Context, in *ListDigestsRequest, opts ...grpc.CallOption) (*ListDigestsResponse, error)
	// GetDigest returns a single digest by Id
	GetDigest(ctx context.Context, in *GetDigestRequest, opts ...grpc.CallOption) (*GetDigestResponse, error)
	// GetDigestArticles returns articles for a digest
	GetDigestArticles(ctx context.Context, in *GetDigestArticlesRequest, opts ...grpc.CallOption) (*GetDigestArticlesResponse, error)
	// GenerateDigest generates a new digest, streaming progress events back to the caller
	GenerateDigest(ctx context.Context, in *GenerateDigestRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DigestProgressEvent], error)
}

type digestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDigestServiceClient(cc grpc.ClientConnInterface) DigestServiceClient {
	return &digestServiceClient{cc}
}

func (c *digestServiceClient) ListDigests(ctx context.Context, in *ListDigestsRequest, opts ...grpc.CallOption) (*ListDigestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDigestsResponse)
	err := c.cc.Invoke(ctx, DigestService_ListDigests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digestServiceClient) GetDigest(ctx context.Context, in *GetDigestRequest, opts ...grpc.CallOption) (*GetDigestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDigestResponse)
	err := c.cc.Invoke(ctx, DigestService_GetDigest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digestServiceClient) GetDigestArticles(ctx context.Context, in *GetDigestArticlesRequest, opts ...grpc.CallOption) (*GetDigestArticlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDigestArticlesResponse)
	err := c.cc.Invoke(ctx, DigestService_GetDigestArticles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digestServiceClient) GenerateDigest(ctx context.Context, in *GenerateDigestRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DigestProgressEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DigestService_ServiceDesc.Streams[0], DigestService_GenerateDigest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateDigestRequest, DigestProgressEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DigestService_GenerateDigestClient = grpc.ServerStreamingClient[DigestProgressEvent]

// DigestServiceServer is the server API for DigestService service.
// All implementations must embed UnimplementedDigestServiceServer
// for forward compatibility.
//
// DigestService provides methods for working with digests
type DigestServiceServer interface {
	// ListDigests retrieves all digests
	ListDigests(context.Context, *ListDigestsRequest) (*ListDigestsResponse, error)
	// GetDigest returns a single digest by Id
	GetDigest(context.Context, *GetDigestRequest) (*GetDigestResponse, error)
	// GetDigestArticles returns articles for a digest
	GetDigestArticles(context.Context, *GetDigestArticlesRequest) (*GetDigestArticlesResponse, error)
	// GenerateDigest generates a new digest, streaming progress events back to the caller
	GenerateDigest(*GenerateDigestRequest, grpc.ServerStreamingServer[DigestProgressEvent]) error
	mustEmbedUnimplementedDigestServiceServer()
}

// UnimplementedDigestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDigestServiceServer struct{}

func (UnimplementedDigestServiceServer) ListDigests(context.Context, *ListDigestsRequest) (*ListDigestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDigests not implemented")
}
func (UnimplementedDigestServiceServer) GetDigest(context.Context, *GetDigestRequest) (*GetDigestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDigest not implemented")
}
func (UnimplementedDigestServiceServer) GetDigestArticles(context.Context, *GetDigestArticlesRequest) (*GetDigestArticlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDigestArticles not implemented")
}
func (UnimplementedDigestServiceServer) GenerateDigest(*GenerateDigestRequest, grpc.ServerStreamingServer[DigestProgressEvent]) error {
	return status.Errorf(codes.Unimplemented, "method GenerateDigest not implemented")
}
func (UnimplementedDigestServiceServer) mustEmbedUnimplementedDigestServiceServer() {}
func (UnimplementedDigestServiceServer) testEmbeddedByValue()                       {}

// UnsafeDigestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DigestServiceServer will
// result in compilation errors.
type UnsafeDigestServiceServer interface {
	mustEmbedUnimplementedDigestServiceServer()
}

func RegisterDigestServiceServer(s grpc.ServiceRegistrar, srv DigestServiceServer) {
	// If the following call pancis, it indicates UnimplementedDigestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DigestService_ServiceDesc, srv)
}

func _DigestService_ListDigests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDigestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigestServiceServer).ListDigests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DigestService_ListDigests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigestServiceServer).ListDigests(ctx, req.(*ListDigestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigestService_GetDigest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDigestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigestServiceServer).GetDigest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DigestService_GetDigest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigestServiceServer).GetDigest(ctx, req.(*GetDigestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigestService_GetDigestArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDigestArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigestServiceServer).GetDigestArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DigestService_GetDigestArticles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigestServiceServer).GetDigestArticles(ctx, req.(*GetDigestArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigestService_GenerateDigest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateDigestRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DigestServiceServer).GenerateDigest(m, &grpc.GenericServerStream[GenerateDigestRequest, DigestProgressEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DigestService_GenerateDigestServer = grpc.ServerStreamingServer[DigestProgressEvent]

// DigestService_ServiceDesc is the grpc.ServiceDesc for DigestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DigestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "downlink.DigestService",
	HandlerType: (*DigestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDigests",
			Handler:    _DigestService_ListDigests_Handler,
		},
		{
			MethodName: "GetDigest",
			Handler:    _DigestService_GetDigest_Handler,
		},
		{
			MethodName: "GetDigestArticles",
			Handler:    _DigestService_GetDigestArticles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateDigest",
			Handler:       _DigestService_GenerateDigest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "digests.proto",
}
