// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: digests.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetDigestRequest represents a request to retrieve a digest by Id
type GetDigestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDigestRequest) Reset() {
	*x = GetDigestRequest{}
	mi := &file_digests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDigestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDigestRequest) ProtoMessage() {}

func (x *GetDigestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_digests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDigestRequest.ProtoReflect.Descriptor instead.
func (*GetDigestRequest) Descriptor() ([]byte, []int) {
	return file_digests_proto_rawDescGZIP(), []int{0}
}

func (x *GetDigestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetDigestResponse represents the response with a digest
type GetDigestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        *Digest                `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDigestResponse) Reset() {
	*x = GetDigestResponse{}
	mi := &file_digests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDigestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDigestResponse) ProtoMessage() {}

func (x *GetDigestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_digests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDigestResponse.ProtoReflect.Descriptor instead.
func (*GetDigestResponse) Descriptor() ([]byte, []int) {
	return file_digests_proto_rawDescGZIP(), []int{1}
}

func (x *GetDigestResponse) GetDigest() *Digest {
	if x != nil {
		return x.Digest
	}
	return nil
}

// GetDigestArticlesRequest represents a request to retrieve articles for a digest
type GetDigestArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DigestId      string                 `protobuf:"bytes,1,opt,name=digest_id,json=digestId,proto3" json:"digest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDigestArticlesRequest) Reset() {
	*x = GetDigestArticlesRequest{}
	mi := &file_digests_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDigestArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDigestArticlesRequest) ProtoMessage() {}

func (x *GetDigestArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_digests_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDigestArticlesRequest.ProtoReflect.Descriptor instead.
func (*GetDigestArticlesRequest) Descriptor() ([]byte, []int) {
	return file_digests_proto_rawDescGZIP(), []int{2}
}

func (x *GetDigestArticlesRequest) GetDigestId() string {
	if x != nil {
		return x.DigestId
	}
	return ""
}

// GetDigestArticlesResponse represents the response with articles for a digest
type GetDigestArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDigestArticlesResponse) Reset() {
	*x = GetDigestArticlesResponse{}
	mi := &file_digests_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDigestArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDigestArticlesResponse) ProtoMessage() {}

func (x *GetDigestArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_digests_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDigestArticlesResponse.ProtoReflect.Descriptor instead.
func (*GetDigestArticlesResponse) Descriptor() ([]byte, []int) {
	return file_digests_proto_rawDescGZIP(), []int{3}
}

func (x *GetDigestArticlesResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

// DeleteDigestRequest represents a request to delete a digest by Id
type DeleteDigestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDigestRequest) Reset() {
	*x = DeleteDigestRequest{}
	mi := &file_digests_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDigestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDigestRequest) ProtoMessage() {}

func (x *DeleteDigestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_digests_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDigestRequest.ProtoReflect.Descriptor instead.
func (*DeleteDigestRequest) Descriptor() ([]byte, []int) {
	return file_digests_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDigestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteAllDigestsRequest represents a request to delete all digests
type DeleteAllDigestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAllDigestsRequest) Reset() {
	*x = DeleteAllDigestsRequest{}
	mi := &file_digests_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAllDigestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllDigestsRequest) ProtoMessage() {}

func (x *DeleteAllDigestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_digests_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllDigestsRequest.ProtoReflect.Descriptor instead.
func (*DeleteAllDigestsRequest) Descriptor() ([]byte, []int) {
	return file_digests_proto_rawDescGZIP(), []int{5}
}

// GenerateDigestRequest represents a request to generate a new digest
type GenerateDigestRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StartTime       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	SkipAnalysis    bool                   `protobuf:"varint,3,opt,name=skip_analysis,json=skipAnalysis,proto3" json:"skip_analysis,omitempty"`
	SkipDuplicates  bool                   `protobuf:"varint,4,opt,name=skip_duplicates,json=skipDuplicates,proto3" json:"skip_duplicates,omitempty"`
	ExcludeDigested bool                   `protobuf:"varint,5,opt,name=exclude_digested,json=excludeDigested,proto3" json:"exclude_digested,omitempty"`
	SkipSummary     bool                   `protobuf:"varint,6,opt,name=skip_summary,json=skipSummary,proto3" json:"skip_summary,omitempty"`
	Theme           string                 `protobuf:"bytes,7,opt,name=theme,proto3" json:"theme,omitempty"`
	OneShotAnalysis bool                   `protobuf:"varint,8,opt,name=one_shot_analysis,json=oneShotAnalysis,proto3" json:"one_shot_analysis,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateDigestRequest) Reset() {
	*x = GenerateDigestRequest{}
	mi := &file_digests_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDigestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDigestRequest) ProtoMessage() {}

func (x *GenerateDigestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_digests_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDigestRequest.ProtoReflect.Descriptor instead.
func (*GenerateDigestRequest) Descriptor() ([]byte, []int) {
	return file_digests_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateDigestRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GenerateDigestRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GenerateDigestRequest) GetSkipAnalysis() bool {
	if x != nil {
		return x.SkipAnalysis
	}
	return false
}

func (x *GenerateDigestRequest) GetSkipDuplicates() bool {
	if x != nil {
		return x.SkipDuplicates
	}
	return false
}

func (x *GenerateDigestRequest) GetExcludeDigested() bool {
	if x != nil {
		return x.ExcludeDigested
	}
	return false
}

func (x *GenerateDigestRequest) GetSkipSummary() bool {
	if x != nil {
		return x.SkipSummary
	}
	return false
}

func (x *GenerateDigestRequest) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *GenerateDigestRequest) GetOneShotAnalysis() bool {
	if x != nil {
		return x.OneShotAnalysis
	}
	return false
}

// GenerateDigestResponse represents the response with the generated digest
type GenerateDigestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        *Digest                `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDigestResponse) Reset() {
	*x = GenerateDigestResponse{}
	mi := &file_digests_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDigestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDigestResponse) ProtoMessage() {}

func (x *GenerateDigestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_digests_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDigestResponse.ProtoReflect.Descriptor instead.
func (*GenerateDigestResponse) Descriptor() ([]byte, []int) {
	return file_digests_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateDigestResponse) GetDigest() *Digest {
	if x != nil {
		return x.Digest
	}
	return nil
}

// DigestProgressEvent is a streaming progress update during digest generation.
// stage values: "fetch" | "analyze" | "analyze_task" | "dedupe" | "summarize" | "store" | "notify" | "done" | "error"
type DigestProgressEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Stage   string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Current uint32                 `protobuf:"varint,3,opt,name=current,proto3" json:"current,omitempty"`
	Total   uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Error   string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Digest  *Digest                `protobuf:"bytes,6,opt,name=digest,proto3" json:"digest,omitempty"`
	// Substep fields (populated when stage="analyze_task")
	TaskName   string `protobuf:"bytes,7,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`       // e.g. "categorize", "key_points", "insights", "summaries", "importance"
	TaskStatus string `protobuf:"bytes,8,opt,name=task_status,json=taskStatus,proto3" json:"task_status,omitempty"` // "started" | "completed" | "error"
	TaskIndex  uint32 `protobuf:"varint,9,opt,name=task_index,json=taskIndex,proto3" json:"task_index,omitempty"`   // 1-based
	TaskTotal  uint32 `protobuf:"varint,10,opt,name=task_total,json=taskTotal,proto3" json:"task_total,omitempty"`  // total tasks in the analysis pipeline
	// Article identity (populated when stage="analyze" or "analyze_task")
	// so clients can distinguish concurrent per-article progress streams.
	ArticleId     string `protobuf:"bytes,11,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	ArticleTitle  string `protobuf:"bytes,12,opt,name=article_title,json=articleTitle,proto3" json:"article_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestProgressEvent) Reset() {
	*x = DigestProgressEvent{}
	mi := &file_digests_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestProgressEvent) ProtoMessage() {}

func (x *DigestProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_digests_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestProgressEvent.ProtoReflect.Descriptor instead.
func (*DigestProgressEvent) Descriptor() ([]byte, []int) {
	return file_digests_proto_rawDescGZIP(), []int{8}
}

func (x *DigestProgressEvent) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *DigestProgressEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DigestProgressEvent) GetCurrent() uint32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *DigestProgressEvent) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DigestProgressEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DigestProgressEvent) GetDigest() *Digest {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *DigestProgressEvent) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *DigestProgressEvent) GetTaskStatus() string {
	if x != nil {
		return x.TaskStatus
	}
	return ""
}

func (x *DigestProgressEvent) GetTaskIndex() uint32 {
	if x != nil {
		return x.TaskIndex
	}
	return 0
}

func (x *DigestProgressEvent) GetTaskTotal() uint32 {
	if x != nil {
		return x.TaskTotal
	}
	return 0
}

func (x *DigestProgressEvent) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *DigestProgressEvent) GetArticleTitle() string {
	if x != nil {
		return x.ArticleTitle
	}
	return ""
}

// ListDigestsRequest represents a request to retrieve all digests
type ListDigestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDigestsRequest) Reset() {
	*x = ListDigestsRequest{}
	mi := &file_digests_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDigestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDigestsRequest) ProtoMessage() {}

func (x *ListDigestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_digests_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDigestsRequest.ProtoReflect.Descriptor instead.
func (*ListDigestsRequest) Descriptor() ([]byte, []int) {
	return file_digests_proto_rawDescGZIP(), []int{9}
}

func (x *ListDigestsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListDigestsResponse represents the response with all digests
type ListDigestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digests       []*Digest              `protobuf:"bytes,1,rep,name=digests,proto3" json:"digests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDigestsResponse) Reset() {
	*x = ListDigestsResponse{}
	mi := &file_digests_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDigestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDigestsResponse) ProtoMessage() {}

func (x *ListDigestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_digests_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDigestsResponse.ProtoReflect.Descriptor instead.
func (*ListDigestsResponse) Descriptor() ([]byte, []int) {
	return file_digests_proto_rawDescGZIP(), []int{10}
}

func (x *ListDigestsResponse) GetDigests() []*Digest {
	if x != nil {
		return x.Digests
	}
	return nil
}

// DigestProviderResult represents a provider's result for a digest
type DigestProviderResult struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DigestId               string                 `protobuf:"bytes,2,opt,name=digest_id,json=digestId,proto3" json:"digest_id,omitempty"`
	ProviderType           string                 `protobuf:"bytes,3,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	ModelName              string                 `protobuf:"bytes,4,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	BriefOverview          string                 `protobuf:"bytes,5,opt,name=brief_overview,json=briefOverview,proto3" json:"brief_overview,omitempty"`
	StandardSynthesis      string                 `protobuf:"bytes,6,opt,name=standard_synthesis,json=standardSynthesis,proto3" json:"standard_synthesis,omitempty"`
	ComprehensiveSynthesis string                 `protobuf:"bytes,7,opt,name=comprehensive_synthesis,json=comprehensiveSynthesis,proto3" json:"comprehensive_synthesis,omitempty"`
	ProcessingTime         float64                `protobuf:"fixed64,8,opt,name=processing_time,json=processingTime,proto3" json:"processing_time,omitempty"`
	Error                  string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt              *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Digest                 *Digest                `protobuf:"bytes,11,opt,name=digest,proto3,oneof" json:"digest,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DigestProviderResult) Reset() {
	*x = DigestProviderResult{}
	mi := &file_digests_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestProviderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestProviderResult) ProtoMessage() {}

func (x *DigestProviderResult) ProtoReflect() protoreflect.Message {
	mi := &file_digests_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestProviderResult.ProtoReflect.Descriptor instead.
func (*DigestProviderResult) Descriptor() ([]byte, []int) {
	return file_digests_proto_rawDescGZIP(), []int{11}
}

func (x *DigestProviderResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DigestProviderResult) GetDigestId() string {
	if x != nil {
		return x.DigestId
	}
	return ""
}

func (x *DigestProviderResult) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *DigestProviderResult) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *DigestProviderResult) GetBriefOverview() string {
	if x != nil {
		return x.BriefOverview
	}
	return ""
}

func (x *DigestProviderResult) GetStandardSynthesis() string {
	if x != nil {
		return x.StandardSynthesis
	}
	return ""
}

func (x *DigestProviderResult) GetComprehensiveSynthesis() string {
	if x != nil {
		return x.ComprehensiveSynthesis
	}
	return ""
}

func (x *DigestProviderResult) GetProcessingTime() float64 {
	if x != nil {
		return x.ProcessingTime
	}
	return 0
}

func (x *DigestProviderResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DigestProviderResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DigestProviderResult) GetDigest() *Digest {
	if x != nil {
		return x.Digest
	}
	return nil
}

// DigestAnalysis links an ArticleAnalysis to a Digest with duplicate metadata
type DigestAnalysis struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DigestId            string                 `protobuf:"bytes,1,opt,name=digest_id,json=digestId,proto3" json:"digest_id,omitempty"`
	AnalysisId          string                 `protobuf:"bytes,2,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	ArticleId           string                 `protobuf:"bytes,3,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	DuplicateGroup      string                 `protobuf:"bytes,4,opt,name=duplicate_group,json=duplicateGroup,proto3" json:"duplicate_group,omitempty"`
	IsMostComprehensive bool                   `protobuf:"varint,5,opt,name=is_most_comprehensive,json=isMostComprehensive,proto3" json:"is_most_comprehensive,omitempty"`
	Analysis            *ArticleAnalysis       `protobuf:"bytes,6,opt,name=analysis,proto3,oneof" json:"analysis,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DigestAnalysis) Reset() {
	*x = DigestAnalysis{}
	mi := &file_digests_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestAnalysis) ProtoMessage() {}

func (x *DigestAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_digests_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestAnalysis.ProtoReflect.Descriptor instead.
func (*DigestAnalysis) Descriptor() ([]byte, []int) {
	return file_digests_proto_rawDescGZIP(), []int{12}
}

func (x *DigestAnalysis) GetDigestId() string {
	if x != nil {
		return x.DigestId
	}
	return ""
}

func (x *DigestAnalysis) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *DigestAnalysis) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *DigestAnalysis) GetDuplicateGroup() string {
	if x != nil {
		return x.DuplicateGroup
	}
	return ""
}

func (x *DigestAnalysis) GetIsMostComprehensive() bool {
	if x != nil {
		return x.IsMostComprehensive
	}
	return false
}

func (x *DigestAnalysis) GetAnalysis() *ArticleAnalysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

// Digest represents a generated digest of articles
type Digest struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Id              string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt       *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ArticleCount    int32                   `protobuf:"varint,3,opt,name=article_count,json=articleCount,proto3" json:"article_count,omitempty"`
	TimeWindow      *durationpb.Duration    `protobuf:"bytes,4,opt,name=time_window,json=timeWindow,proto3" json:"time_window,omitempty"`
	ProviderResults []*DigestProviderResult `protobuf:"bytes,5,rep,name=provider_results,json=providerResults,proto3" json:"provider_results,omitempty"`
	Articles        []*Article              `protobuf:"bytes,6,rep,name=articles,proto3" json:"articles,omitempty"`
	DigestSummary   string                  `protobuf:"bytes,7,opt,name=digest_summary,json=digestSummary,proto3" json:"digest_summary,omitempty"`
	DigestAnalyses  []*DigestAnalysis       `protobuf:"bytes,8,rep,name=digest_analyses,json=digestAnalyses,proto3" json:"digest_analyses,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Digest) Reset() {
	*x = Digest{}
	mi := &file_digests_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Digest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Digest) ProtoMessage() {}

func (x *Digest) ProtoReflect() protoreflect.Message {
	mi := &file_digests_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Digest.ProtoReflect.Descriptor instead.
func (*Digest) Descriptor() ([]byte, []int) {
	return file_digests_proto_rawDescGZIP(), []int{13}
}

func (x *Digest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Digest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Digest) GetArticleCount() int32 {
	if x != nil {
		return x.ArticleCount
	}
	return 0
}

func (x *Digest) GetTimeWindow() *durationpb.Duration {
	if x != nil {
		return x.TimeWindow
	}
	return nil
}

func (x *Digest) GetProviderResults() []*DigestProviderResult {
	if x != nil {
		return x.ProviderResults
	}
	return nil
}

func (x *Digest) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *Digest) GetDigestSummary() string {
	if x != nil {
		return x.DigestSummary
	}
	return ""
}

func (x *Digest) GetDigestAnalyses() []*DigestAnalysis {
	if x != nil {
		return x.DigestAnalyses
	}
	return nil
}

// DigestArticle represents an article included in a digest
type DigestArticle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DigestId      string                 `protobuf:"bytes,1,opt,name=digest_id,json=digestId,proto3" json:"digest_id,omitempty"`
	ArticleId     string                 `protobuf:"bytes,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestArticle) Reset() {
	*x = DigestArticle{}
	mi := &file_digests_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestArticle) ProtoMessage() {}

func (x *DigestArticle) ProtoReflect() protoreflect.Message {
	mi := &file_digests_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestArticle.ProtoReflect.Descriptor instead.
func (*DigestArticle) Descriptor() ([]byte, []int) {
	return file_digests_proto_rawDescGZIP(), []int{14}
}

func (x *DigestArticle) GetDigestId() string {
	if x != nil {
		return x.DigestId
	}
	return ""
}

func (x *DigestArticle) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

var File_digests_proto protoreflect.FileDescriptor

const file_digests_proto_rawDesc = "" +
	"\n" +
	"\rdigests.proto\x12\bdownlink\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x0earticles.proto\x1a\x0eanalysis.proto\"\"\n" +
	"\x10GetDigestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x11GetDigestResponse\x12(\n" +
	"\x06digest\x18\x01 \x01(\v2\x10.downlink.DigestR\x06digest\"7\n" +
	"\x18GetDigestArticlesRequest\x12\x1b\n" +
	"\tdigest_id\x18\x01 \x01(\tR\bdigestId\"J\n" +
	"\x19GetDigestArticlesResponse\x12-\n" +
	"\barticles\x18\x01 \x03(\v2\x11.downlink.ArticleR\barticles\"%\n" +
	"\x13DeleteDigestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17DeleteAllDigestsRequest\"\xe7\x02\n" +
	"\x15GenerateDigestRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12#\n" +
	"\rskip_analysis\x18\x03 \x01(\bR\fskipAnalysis\x12'\n" +
	"\x0fskip_duplicates\x18\x04 \x01(\bR\x0eskipDuplicates\x12)\n" +
	"\x10exclude_digested\x18\x05 \x01(\bR\x0fexcludeDigested\x12!\n" +
	"\fskip_summary\x18\x06 \x01(\bR\vskipSummary\x12\x14\n" +
	"\x05theme\x18\a \x01(\tR\x05theme\x12*\n" +
	"\x11one_shot_analysis\x18\b \x01(\bR\x0foneShotAnalysis\"B\n" +
	"\x16GenerateDigestResponse\x12(\n" +
	"\x06digest\x18\x01 \x01(\v2\x10.downlink.DigestR\x06digest\"\xf5\x02\n" +
	"\x13DigestProgressEvent\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\acurrent\x18\x03 \x01(\rR\acurrent\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12(\n" +
	"\x06digest\x18\x06 \x01(\v2\x10.downlink.DigestR\x06digest\x12\x1b\n" +
	"\ttask_name\x18\a \x01(\tR\btaskName\x12\x1f\n" +
	"\vtask_status\x18\b \x01(\tR\n" +
	"taskStatus\x12\x1d\n" +
	"\n" +
	"task_index\x18\t \x01(\rR\ttaskIndex\x12\x1d\n" +
	"\n" +
	"task_total\x18\n" +
	" \x01(\rR\ttaskTotal\x12\x1d\n" +
	"\n" +
	"article_id\x18\v \x01(\tR\tarticleId\x12#\n" +
	"\rarticle_title\x18\f \x01(\tR\farticleTitle\"*\n" +
	"\x12ListDigestsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\"A\n" +
	"\x13ListDigestsResponse\x12*\n" +
	"\adigests\x18\x01 \x03(\v2\x10.downlink.DigestR\adigests\"\xca\x03\n" +
	"\x14DigestProviderResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdigest_id\x18\x02 \x01(\tR\bdigestId\x12#\n" +
	"\rprovider_type\x18\x03 \x01(\tR\fproviderType\x12\x1d\n" +
	"\n" +
	"model_name\x18\x04 \x01(\tR\tmodelName\x12%\n" +
	"\x0ebrief_overview\x18\x05 \x01(\tR\rbriefOverview\x12-\n" +
	"\x12standard_synthesis\x18\x06 \x01(\tR\x11standardSynthesis\x127\n" +
	"\x17comprehensive_synthesis\x18\a \x01(\tR\x16comprehensiveSynthesis\x12'\n" +
	"\x0fprocessing_time\x18\b \x01(\x01R\x0eprocessingTime\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12-\n" +
	"\x06digest\x18\v \x01(\v2\x10.downlink.DigestH\x00R\x06digest\x88\x01\x01B\t\n" +
	"\a_digest\"\x93\x02\n" +
	"\x0eDigestAnalysis\x12\x1b\n" +
	"\tdigest_id\x18\x01 \x01(\tR\bdigestId\x12\x1f\n" +
	"\vanalysis_id\x18\x02 \x01(\tR\n" +
	"analysisId\x12\x1d\n" +
	"\n" +
	"article_id\x18\x03 \x01(\tR\tarticleId\x12'\n" +
	"\x0fduplicate_group\x18\x04 \x01(\tR\x0eduplicateGroup\x122\n" +
	"\x15is_most_comprehensive\x18\x05 \x01(\bR\x13isMostComprehensive\x12:\n" +
	"\banalysis\x18\x06 \x01(\v2\x19.downlink.ArticleAnalysisH\x00R\banalysis\x88\x01\x01B\v\n" +
	"\t_analysis\"\x98\x03\n" +
	"\x06Digest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12#\n" +
	"\rarticle_count\x18\x03 \x01(\x05R\farticleCount\x12:\n" +
	"\vtime_window\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"timeWindow\x12I\n" +
	"\x10provider_results\x18\x05 \x03(\v2\x1e.downlink.DigestProviderResultR\x0fproviderResults\x12-\n" +
	"\barticles\x18\x06 \x03(\v2\x11.downlink.ArticleR\barticles\x12%\n" +
	"\x0edigest_summary\x18\a \x01(\tR\rdigestSummary\x12A\n" +
	"\x0fdigest_analyses\x18\b \x03(\v2\x18.downlink.DigestAnalysisR\x0edigestAnalyses\"K\n" +
	"\rDigestArticle\x12\x1b\n" +
	"\tdigest_id\x18\x01 \x01(\tR\bdigestId\x12\x1d\n" +
	"\n" +
	"article_id\x18\x02 \x01(\tR\tarticleId2\xdb\x02\n" +
	"\rDigestService\x12L\n" +
	"\vListDigests\x12\x1c.downlink.ListDigestsRequest\x1a\x1d.downlink.ListDigestsResponse\"\x00\x12F\n" +
	"\tGetDigest\x12\x1a.downlink.GetDigestRequest\x1a\x1b.downlink.GetDigestResponse\"\x00\x12^\n" +
	"\x11GetDigestArticles\x12\".downlink.GetDigestArticlesRequest\x1a#.downlink.GetDigestArticlesResponse\"\x00\x12T\n" +
	"\x0eGenerateDigest\x12\x1f.downlink.GenerateDigestRequest\x1a\x1d.downlink.DigestProgressEvent\"\x000\x01B\tZ\aprotos/b\x06proto3"

var (
	file_digests_proto_rawDescOnce sync.Once
	file_digests_proto_rawDescData []byte
)

func file_digests_proto_rawDescGZIP() []byte {
	file_digests_proto_rawDescOnce.Do(func() {
		file_digests_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_digests_proto_rawDesc), len(file_digests_proto_rawDesc)))
	})
	return file_digests_proto_rawDescData
}

var file_digests_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_digests_proto_goTypes = []any{
	(*GetDigestRequest)(nil),          // 0: downlink.GetDigestRequest
	(*GetDigestResponse)(nil),         // 1: downlink.GetDigestResponse
	(*GetDigestArticlesRequest)(nil),  // 2: downlink.GetDigestArticlesRequest
	(*GetDigestArticlesResponse)(nil), // 3: downlink.GetDigestArticlesResponse
	(*DeleteDigestRequest)(nil),       // 4: downlink.DeleteDigestRequest
	(*DeleteAllDigestsRequest)(nil),   // 5: downlink.DeleteAllDigestsRequest
	(*GenerateDigestRequest)(nil),     // 6: downlink.GenerateDigestRequest
	(*GenerateDigestResponse)(nil),    // 7: downlink.GenerateDigestResponse
	(*DigestProgressEvent)(nil),       // 8: downlink.DigestProgressEvent
	(*ListDigestsRequest)(nil),        // 9: downlink.ListDigestsRequest
	(*ListDigestsResponse)(nil),       // 10: downlink.ListDigestsResponse
	(*DigestProviderResult)(nil),      // 11: downlink.DigestProviderResult
	(*DigestAnalysis)(nil),            // 12: downlink.DigestAnalysis
	(*Digest)(nil),                    // 13: downlink.Digest
	(*DigestArticle)(nil),             // 14: downlink.DigestArticle
	(*Article)(nil),                   // 15: downlink.Article
	(*timestamppb.Timestamp)(nil),     // 16: google.protobuf.Timestamp
	(*ArticleAnalysis)(nil),           // 17: downlink.ArticleAnalysis
	(*durationpb.Duration)(nil),       // 18: google.protobuf.Duration
}
var file_digests_proto_depIdxs = []int32{
	13, // 0: downlink.GetDigestResponse.digest:type_name -> downlink.Digest
	15, // 1: downlink.GetDigestArticlesResponse.articles:type_name -> downlink.Article
	16, // 2: downlink.GenerateDigestRequest.start_time:type_name -> google.protobuf.Timestamp
	16, // 3: downlink.GenerateDigestRequest.end_time:type_name -> google.protobuf.Timestamp
	13, // 4: downlink.GenerateDigestResponse.digest:type_name -> downlink.Digest
	13, // 5: downlink.DigestProgressEvent.digest:type_name -> downlink.Digest
	13, // 6: downlink.ListDigestsResponse.digests:type_name -> downlink.Digest
	16, // 7: downlink.DigestProviderResult.created_at:type_name -> google.protobuf.Timestamp
	13, // 8: downlink.DigestProviderResult.digest:type_name -> downlink.Digest
	17, // 9: downlink.DigestAnalysis.analysis:type_name -> downlink.ArticleAnalysis
	16, // 10: downlink.Digest.created_at:type_name -> google.protobuf.Timestamp
	18, // 11: downlink.Digest.time_window:type_name -> google.protobuf.Duration
	11, // 12: downlink.Digest.provider_results:type_name -> downlink.DigestProviderResult
	15, // 13: downlink.Digest.articles:type_name -> downlink.Article
	12, // 14: downlink.Digest.digest_analyses:type_name -> downlink.DigestAnalysis
	9,  // 15: downlink.DigestService.ListDigests:input_type -> downlink.ListDigestsRequest
	0,  // 16: downlink.DigestService.GetDigest:input_type -> downlink.GetDigestRequest
	2,  // 17: downlink.DigestService.GetDigestArticles:input_type -> downlink.GetDigestArticlesRequest
	6,  // 18: downlink.DigestService.GenerateDigest:input_type -> downlink.GenerateDigestRequest
	10, // 19: downlink.DigestService.ListDigests:output_type -> downlink.ListDigestsResponse
	1,  // 20: downlink.DigestService.GetDigest:output_type -> downlink.GetDigestResponse
	3,  // 21: downlink.DigestService.GetDigestArticles:output_type -> downlink.GetDigestArticlesResponse
	8,  // 22: downlink.DigestService.GenerateDigest:output_type -> downlink.DigestProgressEvent
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_digests_proto_init() }
func file_digests_proto_init() {
	if File_digests_proto != nil {
		return
	}
	file_articles_proto_init()
	file_analysis_proto_init()
	file_digests_proto_msgTypes[11].OneofWrappers = []any{}
	file_digests_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_digests_proto_rawDesc), len(file_digests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_digests_proto_goTypes,
		DependencyIndexes: file_digests_proto_depIdxs,
		MessageInfos:      file_digests_proto_msgTypes,
	}.Build()
	File_digests_proto = out.File
	file_digests_proto_goTypes = nil
	file_digests_proto_depIdxs = nil
}
