// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: feeds.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FeedsService_ListFeeds_FullMethodName          = "/downlink.FeedsService/ListFeeds"
	FeedsService_RegisterFeed_FullMethodName       = "/downlink.FeedsService/RegisterFeed"
	FeedsService_RefreshAllFeeds_FullMethodName    = "/downlink.FeedsService/RefreshAllFeeds"
	FeedsService_RefreshFeed_FullMethodName        = "/downlink.FeedsService/RefreshFeed"
	FeedsService_InspectFeed_FullMethodName        = "/downlink.FeedsService/InspectFeed"
	FeedsService_InspectArticle_FullMethodName     = "/downlink.FeedsService/InspectArticle"
	FeedsService_AutoConfigFeed_FullMethodName     = "/downlink.FeedsService/AutoConfigFeed"
	FeedsService_DeleteFeed_FullMethodName         = "/downlink.FeedsService/DeleteFeed"
	FeedsService_ApplyFeeds_FullMethodName         = "/downlink.FeedsService/ApplyFeeds"
	FeedsService_DeleteFeeds_FullMethodName        = "/downlink.FeedsService/DeleteFeeds"
	FeedsService_BackfillFeedTopics_FullMethodName = "/downlink.FeedsService/BackfillFeedTopics"
)

// FeedsServiceClient is the client API for FeedsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FeedsService provides methods for working with feeds
type FeedsServiceClient interface {
	// ListFeeds returns all registered feeds
	ListFeeds(ctx context.Context, in *ListFeedsRequest, opts ...grpc.CallOption) (*ListFeedsResponse, error)
	// RegisterFeed adds a new feed to be monitored
	RegisterFeed(ctx context.Context, in *RegisterFeedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// RefreshAllFeeds triggers a refresh of all registered feeds, streaming per-feed results
	RefreshAllFeeds(ctx context.Context, in *RefreshAllFeedsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RefreshAllFeedsEvent], error)
	// RefreshFeed refreshes a specific feed with optional time window filtering
	RefreshFeed(ctx context.Context, in *RefreshFeedRequest, opts ...grpc.CallOption) (*RefreshFeedResponse, error)
	// InspectFeed fetches and parses a feed URL (read-only, pre-registration),
	// returning a diagnosis plus sample article links for building a feed config.
	InspectFeed(ctx context.Context, in *InspectFeedRequest, opts ...grpc.CallOption) (*InspectFeedResponse, error)
	// InspectArticle scrapes a single article URL in a given mode and, when
	// selectors are supplied, returns the extracted content for selector testing.
	InspectArticle(ctx context.Context, in *InspectArticleRequest, opts ...grpc.CallOption) (*InspectArticleResponse, error)
	// AutoConfigFeed runs the server-side LLM agent that discovers a feed's selectors,
	// scraping mode, and headers on its own, streaming progress then the final config.
	AutoConfigFeed(ctx context.Context, in *AutoConfigFeedRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AutoConfigFeedEvent], error)
	// DeleteFeed removes a feed from both the models and the database
	DeleteFeed(ctx context.Context, in *DeleteFeedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ApplyFeeds reconciles the database to match the desired set of feeds:
	// feeds in the request are created/updated, feeds absent from it are disabled.
	ApplyFeeds(ctx context.Context, in *ApplyFeedsRequest, opts ...grpc.CallOption) (*ApplyFeedsResponse, error)
	// DeleteFeeds removes the given feeds (by id) from the database
	DeleteFeeds(ctx context.Context, in *DeleteFeedsRequest, opts ...grpc.CallOption) (*DeleteFeedsResponse, error)
	// BackfillFeedTopics derives topic labels for the given feeds via the LLM,
	// streaming one event per feed. Read-only: it returns suggestions, the caller
	// writes them back to feeds.yml.
	BackfillFeedTopics(ctx context.Context, in *BackfillFeedTopicsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackfillFeedTopicsEvent], error)
}

type feedsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeedsServiceClient(cc grpc.ClientConnInterface) FeedsServiceClient {
	return &feedsServiceClient{cc}
}

func (c *feedsServiceClient) ListFeeds(ctx context.Context, in *ListFeedsRequest, opts ...grpc.CallOption) (*ListFeedsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFeedsResponse)
	err := c.cc.Invoke(ctx, FeedsService_ListFeeds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsServiceClient) RegisterFeed(ctx context.Context, in *RegisterFeedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FeedsService_RegisterFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsServiceClient) RefreshAllFeeds(ctx context.Context, in *RefreshAllFeedsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RefreshAllFeedsEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FeedsService_ServiceDesc.Streams[0], FeedsService_RefreshAllFeeds_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RefreshAllFeedsRequest, RefreshAllFeedsEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FeedsService_RefreshAllFeedsClient = grpc.ServerStreamingClient[RefreshAllFeedsEvent]

func (c *feedsServiceClient) RefreshFeed(ctx context.Context, in *RefreshFeedRequest, opts ...grpc.CallOption) (*RefreshFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshFeedResponse)
	err := c.cc.Invoke(ctx, FeedsService_RefreshFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsServiceClient) InspectFeed(ctx context.Context, in *InspectFeedRequest, opts ...grpc.CallOption) (*InspectFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectFeedResponse)
	err := c.cc.Invoke(ctx, FeedsService_InspectFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsServiceClient) InspectArticle(ctx context.Context, in *InspectArticleRequest, opts ...grpc.CallOption) (*InspectArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectArticleResponse)
	err := c.cc.Invoke(ctx, FeedsService_InspectArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsServiceClient) AutoConfigFeed(ctx context.Context, in *AutoConfigFeedRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AutoConfigFeedEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FeedsService_ServiceDesc.Streams[1], FeedsService_AutoConfigFeed_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AutoConfigFeedRequest, AutoConfigFeedEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FeedsService_AutoConfigFeedClient = grpc.ServerStreamingClient[AutoConfigFeedEvent]

func (c *feedsServiceClient) DeleteFeed(ctx context.Context, in *DeleteFeedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FeedsService_DeleteFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsServiceClient) ApplyFeeds(ctx context.Context, in *ApplyFeedsRequest, opts ...grpc.CallOption) (*ApplyFeedsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyFeedsResponse)
	err := c.cc.Invoke(ctx, FeedsService_ApplyFeeds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsServiceClient) DeleteFeeds(ctx context.Context, in *DeleteFeedsRequest, opts ...grpc.CallOption) (*DeleteFeedsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFeedsResponse)
	err := c.cc.Invoke(ctx, FeedsService_DeleteFeeds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedsServiceClient) BackfillFeedTopics(ctx context.Context, in *BackfillFeedTopicsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackfillFeedTopicsEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FeedsService_ServiceDesc.Streams[2], FeedsService_BackfillFeedTopics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BackfillFeedTopicsRequest, BackfillFeedTopicsEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FeedsService_BackfillFeedTopicsClient = grpc.ServerStreamingClient[BackfillFeedTopicsEvent]

// FeedsServiceServer is the server API for FeedsService service.
// All implementations must embed UnimplementedFeedsServiceServer
// for forward compatibility.
//
// FeedsService provides methods for working with feeds
type FeedsServiceServer interface {
	// ListFeeds returns all registered feeds
	ListFeeds(context.Context, *ListFeedsRequest) (*ListFeedsResponse, error)
	// RegisterFeed adds a new feed to be monitored
	RegisterFeed(context.Context, *RegisterFeedRequest) (*emptypb.Empty, error)
	// RefreshAllFeeds triggers a refresh of all registered feeds, streaming per-feed results
	RefreshAllFeeds(*RefreshAllFeedsRequest, grpc.ServerStreamingServer[RefreshAllFeedsEvent]) error
	// RefreshFeed refreshes a specific feed with optional time window filtering
	RefreshFeed(context.Context, *RefreshFeedRequest) (*RefreshFeedResponse, error)
	// InspectFeed fetches and parses a feed URL (read-only, pre-registration),
	// returning a diagnosis plus sample article links for building a feed config.
	InspectFeed(context.Context, *InspectFeedRequest) (*InspectFeedResponse, error)
	// InspectArticle scrapes a single article URL in a given mode and, when
	// selectors are supplied, returns the extracted content for selector testing.
	InspectArticle(context.Context, *InspectArticleRequest) (*InspectArticleResponse, error)
	// AutoConfigFeed runs the server-side LLM agent that discovers a feed's selectors,
	// scraping mode, and headers on its own, streaming progress then the final config.
	AutoConfigFeed(*AutoConfigFeedRequest, grpc.ServerStreamingServer[AutoConfigFeedEvent]) error
	// DeleteFeed removes a feed from both the models and the database
	DeleteFeed(context.Context, *DeleteFeedRequest) (*emptypb.Empty, error)
	// ApplyFeeds reconciles the database to match the desired set of feeds:
	// feeds in the request are created/updated, feeds absent from it are disabled.
	ApplyFeeds(context.Context, *ApplyFeedsRequest) (*ApplyFeedsResponse, error)
	// DeleteFeeds removes the given feeds (by id) from the database
	DeleteFeeds(context.Context, *DeleteFeedsRequest) (*DeleteFeedsResponse, error)
	// BackfillFeedTopics derives topic labels for the given feeds via the LLM,
	// streaming one event per feed. Read-only: it returns suggestions, the caller
	// writes them back to feeds.yml.
	BackfillFeedTopics(*BackfillFeedTopicsRequest, grpc.ServerStreamingServer[BackfillFeedTopicsEvent]) error
	mustEmbedUnimplementedFeedsServiceServer()
}

// UnimplementedFeedsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeedsServiceServer struct{}

func (UnimplementedFeedsServiceServer) ListFeeds(context.Context, *ListFeedsRequest) (*ListFeedsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFeeds not implemented")
}
func (UnimplementedFeedsServiceServer) RegisterFeed(context.Context, *RegisterFeedRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterFeed not implemented")
}
func (UnimplementedFeedsServiceServer) RefreshAllFeeds(*RefreshAllFeedsRequest, grpc.ServerStreamingServer[RefreshAllFeedsEvent]) error {
	return status.Error(codes.Unimplemented, "method RefreshAllFeeds not implemented")
}
func (UnimplementedFeedsServiceServer) RefreshFeed(context.Context, *RefreshFeedRequest) (*RefreshFeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshFeed not implemented")
}
func (UnimplementedFeedsServiceServer) InspectFeed(context.Context, *InspectFeedRequest) (*InspectFeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectFeed not implemented")
}
func (UnimplementedFeedsServiceServer) InspectArticle(context.Context, *InspectArticleRequest) (*InspectArticleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectArticle not implemented")
}
func (UnimplementedFeedsServiceServer) AutoConfigFeed(*AutoConfigFeedRequest, grpc.ServerStreamingServer[AutoConfigFeedEvent]) error {
	return status.Error(codes.Unimplemented, "method AutoConfigFeed not implemented")
}
func (UnimplementedFeedsServiceServer) DeleteFeed(context.Context, *DeleteFeedRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFeed not implemented")
}
func (UnimplementedFeedsServiceServer) ApplyFeeds(context.Context, *ApplyFeedsRequest) (*ApplyFeedsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyFeeds not implemented")
}
func (UnimplementedFeedsServiceServer) DeleteFeeds(context.Context, *DeleteFeedsRequest) (*DeleteFeedsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFeeds not implemented")
}
func (UnimplementedFeedsServiceServer) BackfillFeedTopics(*BackfillFeedTopicsRequest, grpc.ServerStreamingServer[BackfillFeedTopicsEvent]) error {
	return status.Error(codes.Unimplemented, "method BackfillFeedTopics not implemented")
}
func (UnimplementedFeedsServiceServer) mustEmbedUnimplementedFeedsServiceServer() {}
func (UnimplementedFeedsServiceServer) testEmbeddedByValue()                      {}

// UnsafeFeedsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeedsServiceServer will
// result in compilation errors.
type UnsafeFeedsServiceServer interface {
	mustEmbedUnimplementedFeedsServiceServer()
}

func RegisterFeedsServiceServer(s grpc.ServiceRegistrar, srv FeedsServiceServer) {
	// If the following call panics, it indicates UnimplementedFeedsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeedsService_ServiceDesc, srv)
}

func _FeedsService_ListFeeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeedsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServiceServer).ListFeeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedsService_ListFeeds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServiceServer).ListFeeds(ctx, req.(*ListFeedsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedsService_RegisterFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServiceServer).RegisterFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedsService_RegisterFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServiceServer).RegisterFeed(ctx, req.(*RegisterFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedsService_RefreshAllFeeds_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RefreshAllFeedsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FeedsServiceServer).RefreshAllFeeds(m, &grpc.GenericServerStream[RefreshAllFeedsRequest, RefreshAllFeedsEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FeedsService_RefreshAllFeedsServer = grpc.ServerStreamingServer[RefreshAllFeedsEvent]

func _FeedsService_RefreshFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServiceServer).RefreshFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedsService_RefreshFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServiceServer).RefreshFeed(ctx, req.(*RefreshFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedsService_InspectFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServiceServer).InspectFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedsService_InspectFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServiceServer).InspectFeed(ctx, req.(*InspectFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedsService_InspectArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServiceServer).InspectArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedsService_InspectArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServiceServer).InspectArticle(ctx, req.(*InspectArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedsService_AutoConfigFeed_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AutoConfigFeedRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FeedsServiceServer).AutoConfigFeed(m, &grpc.GenericServerStream[AutoConfigFeedRequest, AutoConfigFeedEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FeedsService_AutoConfigFeedServer = grpc.ServerStreamingServer[AutoConfigFeedEvent]

func _FeedsService_DeleteFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServiceServer).DeleteFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedsService_DeleteFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServiceServer).DeleteFeed(ctx, req.(*DeleteFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedsService_ApplyFeeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyFeedsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServiceServer).ApplyFeeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedsService_ApplyFeeds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServiceServer).ApplyFeeds(ctx, req.(*ApplyFeedsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedsService_DeleteFeeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeedsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedsServiceServer).DeleteFeeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedsService_DeleteFeeds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedsServiceServer).DeleteFeeds(ctx, req.(*DeleteFeedsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedsService_BackfillFeedTopics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BackfillFeedTopicsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FeedsServiceServer).BackfillFeedTopics(m, &grpc.GenericServerStream[BackfillFeedTopicsRequest, BackfillFeedTopicsEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FeedsService_BackfillFeedTopicsServer = grpc.ServerStreamingServer[BackfillFeedTopicsEvent]

// FeedsService_ServiceDesc is the grpc.ServiceDesc for FeedsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeedsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "downlink.FeedsService",
	HandlerType: (*FeedsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFeeds",
			Handler:    _FeedsService_ListFeeds_Handler,
		},
		{
			MethodName: "RegisterFeed",
			Handler:    _FeedsService_RegisterFeed_Handler,
		},
		{
			MethodName: "RefreshFeed",
			Handler:    _FeedsService_RefreshFeed_Handler,
		},
		{
			MethodName: "InspectFeed",
			Handler:    _FeedsService_InspectFeed_Handler,
		},
		{
			MethodName: "InspectArticle",
			Handler:    _FeedsService_InspectArticle_Handler,
		},
		{
			MethodName: "DeleteFeed",
			Handler:    _FeedsService_DeleteFeed_Handler,
		},
		{
			MethodName: "ApplyFeeds",
			Handler:    _FeedsService_ApplyFeeds_Handler,
		},
		{
			MethodName: "DeleteFeeds",
			Handler:    _FeedsService_DeleteFeeds_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RefreshAllFeeds",
			Handler:       _FeedsService_RefreshAllFeeds_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AutoConfigFeed",
			Handler:       _FeedsService_AutoConfigFeed_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BackfillFeedTopics",
			Handler:       _FeedsService_BackfillFeedTopics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "feeds.proto",
}
