// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: feeds.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefreshEventType int32

const (
	RefreshEventType_STARTED   RefreshEventType = 0 // feed has been queued and is now in progress
	RefreshEventType_COMPLETED RefreshEventType = 1 // feed finished (result fields are populated)
)

// Enum value maps for RefreshEventType.
var (
	RefreshEventType_name = map[int32]string{
		0: "STARTED",
		1: "COMPLETED",
	}
	RefreshEventType_value = map[string]int32{
		"STARTED":   0,
		"COMPLETED": 1,
	}
)

func (x RefreshEventType) Enum() *RefreshEventType {
	p := new(RefreshEventType)
	*p = x
	return p
}

func (x RefreshEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefreshEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_feeds_proto_enumTypes[0].Descriptor()
}

func (RefreshEventType) Type() protoreflect.EnumType {
	return &file_feeds_proto_enumTypes[0]
}

func (x RefreshEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefreshEventType.Descriptor instead.
func (RefreshEventType) EnumDescriptor() ([]byte, []int) {
	return file_feeds_proto_rawDescGZIP(), []int{0}
}

// ListFeedsRequest is the request for the ListFeeds method
type ListFeedsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedsRequest) Reset() {
	*x = ListFeedsRequest{}
	mi := &file_feeds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedsRequest) ProtoMessage() {}

func (x *ListFeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feeds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedsRequest.ProtoReflect.Descriptor instead.
func (*ListFeedsRequest) Descriptor() ([]byte, []int) {
	return file_feeds_proto_rawDescGZIP(), []int{0}
}

// ListFeedsResponse is the response for the ListFeeds method
type ListFeedsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feeds         []*Feed                `protobuf:"bytes,1,rep,name=feeds,proto3" json:"feeds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedsResponse) Reset() {
	*x = ListFeedsResponse{}
	mi := &file_feeds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedsResponse) ProtoMessage() {}

func (x *ListFeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feeds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedsResponse.ProtoReflect.Descriptor instead.
func (*ListFeedsResponse) Descriptor() ([]byte, []int) {
	return file_feeds_proto_rawDescGZIP(), []int{1}
}

func (x *ListFeedsResponse) GetFeeds() []*Feed {
	if x != nil {
		return x.Feeds
	}
	return nil
}

// RegisterFeedRequest is the request for the RegisterFeed method
type RegisterFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedConfig    *FeedConfig            `protobuf:"bytes,1,opt,name=feed_config,json=feedConfig,proto3" json:"feed_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterFeedRequest) Reset() {
	*x = RegisterFeedRequest{}
	mi := &file_feeds_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFeedRequest) ProtoMessage() {}

func (x *RegisterFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feeds_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFeedRequest.ProtoReflect.Descriptor instead.
func (*RegisterFeedRequest) Descriptor() ([]byte, []int) {
	return file_feeds_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterFeedRequest) GetFeedConfig() *FeedConfig {
	if x != nil {
		return x.FeedConfig
	}
	return nil
}

// RefreshAllFeedsRequest is the request for the RefreshAllFeeds method
type RefreshAllFeedsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAllFeedsRequest) Reset() {
	*x = RefreshAllFeedsRequest{}
	mi := &file_feeds_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAllFeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAllFeedsRequest) ProtoMessage() {}

func (x *RefreshAllFeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feeds_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAllFeedsRequest.ProtoReflect.Descriptor instead.
func (*RefreshAllFeedsRequest) Descriptor() ([]byte, []int) {
	return file_feeds_proto_rawDescGZIP(), []int{3}
}

// RefreshFeedResponse carries per-feed stats returned after a refresh
type RefreshFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedId        string                 `protobuf:"bytes,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	FeedTitle     string                 `protobuf:"bytes,2,opt,name=feed_title,json=feedTitle,proto3" json:"feed_title,omitempty"`
	TotalFetched  int32                  `protobuf:"varint,3,opt,name=total_fetched,json=totalFetched,proto3" json:"total_fetched,omitempty"`
	Stored        int32                  `protobuf:"varint,4,opt,name=stored,proto3" json:"stored,omitempty"`
	Skipped       int32                  `protobuf:"varint,5,opt,name=skipped,proto3" json:"skipped,omitempty"`
	Errors        []string               `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshFeedResponse) Reset() {
	*x = RefreshFeedResponse{}
	mi := &file_feeds_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshFeedResponse) ProtoMessage() {}

func (x *RefreshFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feeds_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshFeedResponse.ProtoReflect.Descriptor instead.
func (*RefreshFeedResponse) Descriptor() ([]byte, []int) {
	return file_feeds_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshFeedResponse) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

func (x *RefreshFeedResponse) GetFeedTitle() string {
	if x != nil {
		return x.FeedTitle
	}
	return ""
}

func (x *RefreshFeedResponse) GetTotalFetched() int32 {
	if x != nil {
		return x.TotalFetched
	}
	return 0
}

func (x *RefreshFeedResponse) GetStored() int32 {
	if x != nil {
		return x.Stored
	}
	return 0
}

func (x *RefreshFeedResponse) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

func (x *RefreshFeedResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// RefreshAllFeedsEvent is streamed once per feed on start and on completion
type RefreshAllFeedsEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *RefreshFeedResponse   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Completed     int32                  `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"` // feeds completed so far (COMPLETED events only)
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`         // total feeds being refreshed
	EventType     RefreshEventType       `protobuf:"varint,4,opt,name=event_type,json=eventType,proto3,enum=downlink.RefreshEventType" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAllFeedsEvent) Reset() {
	*x = RefreshAllFeedsEvent{}
	mi := &file_feeds_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAllFeedsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAllFeedsEvent) ProtoMessage() {}

func (x *RefreshAllFeedsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_feeds_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAllFeedsEvent.ProtoReflect.Descriptor instead.
func (*RefreshAllFeedsEvent) Descriptor() ([]byte, []int) {
	return file_feeds_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshAllFeedsEvent) GetResult() *RefreshFeedResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RefreshAllFeedsEvent) GetCompleted() int32 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *RefreshAllFeedsEvent) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RefreshAllFeedsEvent) GetEventType() RefreshEventType {
	if x != nil {
		return x.EventType
	}
	return RefreshEventType_STARTED
}

// RefreshFeedRequest is the request for the RefreshFeed method
type RefreshFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedId        string                 `protobuf:"bytes,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`            // Optional: start of time window
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`                // Optional: end of time window
	Overwrite     bool                   `protobuf:"varint,4,opt,name=overwrite,proto3" json:"overwrite,omitempty"` // Optional: overwrite existing articles
	Restore       bool                   `protobuf:"varint,5,opt,name=restore,proto3" json:"restore,omitempty"`     // Optional: overwrite only articles with no content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshFeedRequest) Reset() {
	*x = RefreshFeedRequest{}
	mi := &file_feeds_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshFeedRequest) ProtoMessage() {}

func (x *RefreshFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feeds_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshFeedRequest.ProtoReflect.Descriptor instead.
func (*RefreshFeedRequest) Descriptor() ([]byte, []int) {
	return file_feeds_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshFeedRequest) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

func (x *RefreshFeedRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *RefreshFeedRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *RefreshFeedRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

func (x *RefreshFeedRequest) GetRestore() bool {
	if x != nil {
		return x.Restore
	}
	return false
}

// DeleteFeedRequest is the request for the DeleteFeed method
type DeleteFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedId        string                 `protobuf:"bytes,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFeedRequest) Reset() {
	*x = DeleteFeedRequest{}
	mi := &file_feeds_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFeedRequest) ProtoMessage() {}

func (x *DeleteFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feeds_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFeedRequest.ProtoReflect.Descriptor instead.
func (*DeleteFeedRequest) Descriptor() ([]byte, []int) {
	return file_feeds_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFeedRequest) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

// ApplyFeedsRequest carries the desired set of feeds to reconcile against
type ApplyFeedsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Feeds            []*FeedConfig          `protobuf:"bytes,1,rep,name=feeds,proto3" json:"feeds,omitempty"`
	DefaultSelectors *Selectors             `protobuf:"bytes,2,opt,name=default_selectors,json=defaultSelectors,proto3" json:"default_selectors,omitempty"` // baked into feeds lacking their own selectors
	DryRun           bool                   `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`                              // when true, compute the plan but make no changes
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApplyFeedsRequest) Reset() {
	*x = ApplyFeedsRequest{}
	mi := &file_feeds_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyFeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyFeedsRequest) ProtoMessage() {}

func (x *ApplyFeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feeds_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyFeedsRequest.ProtoReflect.Descriptor instead.
func (*ApplyFeedsRequest) Descriptor() ([]byte, []int) {
	return file_feeds_proto_rawDescGZIP(), []int{8}
}

func (x *ApplyFeedsRequest) GetFeeds() []*FeedConfig {
	if x != nil {
		return x.Feeds
	}
	return nil
}

func (x *ApplyFeedsRequest) GetDefaultSelectors() *Selectors {
	if x != nil {
		return x.DefaultSelectors
	}
	return nil
}

func (x *ApplyFeedsRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

// ApplyFeedsResponse reports the (would-be, when dry_run) reconciliation outcome.
// Each list carries human-readable identifiers (e.g. "title — url"), not ids.
type ApplyFeedsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       []string               `protobuf:"bytes,1,rep,name=created,proto3" json:"created,omitempty"`
	Updated       []string               `protobuf:"bytes,2,rep,name=updated,proto3" json:"updated,omitempty"`
	Disabled      []string               `protobuf:"bytes,3,rep,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyFeedsResponse) Reset() {
	*x = ApplyFeedsResponse{}
	mi := &file_feeds_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyFeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyFeedsResponse) ProtoMessage() {}

func (x *ApplyFeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feeds_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyFeedsResponse.ProtoReflect.Descriptor instead.
func (*ApplyFeedsResponse) Descriptor() ([]byte, []int) {
	return file_feeds_proto_rawDescGZIP(), []int{9}
}

func (x *ApplyFeedsResponse) GetCreated() []string {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *ApplyFeedsResponse) GetUpdated() []string {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *ApplyFeedsResponse) GetDisabled() []string {
	if x != nil {
		return x.Disabled
	}
	return nil
}

// DeleteFeedsRequest carries the ids of the feeds to delete
type DeleteFeedsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedIds       []string               `protobuf:"bytes,1,rep,name=feed_ids,json=feedIds,proto3" json:"feed_ids,omitempty"`
	DryRun        bool                   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"` // when true, report what would be deleted but make no changes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFeedsRequest) Reset() {
	*x = DeleteFeedsRequest{}
	mi := &file_feeds_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFeedsRequest) ProtoMessage() {}

func (x *DeleteFeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feeds_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFeedsRequest.ProtoReflect.Descriptor instead.
func (*DeleteFeedsRequest) Descriptor() ([]byte, []int) {
	return file_feeds_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteFeedsRequest) GetFeedIds() []string {
	if x != nil {
		return x.FeedIds
	}
	return nil
}

func (x *DeleteFeedsRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

// DeleteFeedsResponse reports the (would-be, when dry_run) deletion outcome
type DeleteFeedsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       []string               `protobuf:"bytes,1,rep,name=deleted,proto3" json:"deleted,omitempty"`
	NotFound      []string               `protobuf:"bytes,2,rep,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFeedsResponse) Reset() {
	*x = DeleteFeedsResponse{}
	mi := &file_feeds_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFeedsResponse) ProtoMessage() {}

func (x *DeleteFeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feeds_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFeedsResponse.ProtoReflect.Descriptor instead.
func (*DeleteFeedsResponse) Descriptor() ([]byte, []int) {
	return file_feeds_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteFeedsResponse) GetDeleted() []string {
	if x != nil {
		return x.Deleted
	}
	return nil
}

func (x *DeleteFeedsResponse) GetNotFound() []string {
	if x != nil {
		return x.NotFound
	}
	return nil
}

// FeedGroup represents a group of feeds
type FeedGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Feeds         []*Feed                `protobuf:"bytes,5,rep,name=feeds,proto3" json:"feeds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedGroup) Reset() {
	*x = FeedGroup{}
	mi := &file_feeds_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedGroup) ProtoMessage() {}

func (x *FeedGroup) ProtoReflect() protoreflect.Message {
	mi := &file_feeds_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedGroup.ProtoReflect.Descriptor instead.
func (*FeedGroup) Descriptor() ([]byte, []int) {
	return file_feeds_proto_rawDescGZIP(), []int{12}
}

func (x *FeedGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeedGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeedGroup) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *FeedGroup) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *FeedGroup) GetFeeds() []*Feed {
	if x != nil {
		return x.Feeds
	}
	return nil
}

// Feed represents a feed with its metadata
type Feed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	LastFetch     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_fetch,json=lastFetch,proto3" json:"last_fetch,omitempty"`
	Scraper       map[string]*anypb.Any  `protobuf:"bytes,6,rep,name=scraper,proto3" json:"scraper,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Enabled       bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	GroupId       string                 `protobuf:"bytes,8,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Articles      []*Article             `protobuf:"bytes,9,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feed) Reset() {
	*x = Feed{}
	mi := &file_feeds_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feed) ProtoMessage() {}

func (x *Feed) ProtoReflect() protoreflect.Message {
	mi := &file_feeds_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feed.ProtoReflect.Descriptor instead.
func (*Feed) Descriptor() ([]byte, []int) {
	return file_feeds_proto_rawDescGZIP(), []int{13}
}

func (x *Feed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Feed) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Feed) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Feed) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Feed) GetLastFetch() *timestamppb.Timestamp {
	if x != nil {
		return x.LastFetch
	}
	return nil
}

func (x *Feed) GetScraper() map[string]*anypb.Any {
	if x != nil {
		return x.Scraper
	}
	return nil
}

func (x *Feed) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Feed) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Feed) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

// FeedItem represents a generic feed item returned by a scraper
type FeedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Link          string                 `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Category      string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	HeroImage     string                 `protobuf:"bytes,8,opt,name=hero_image,json=heroImage,proto3" json:"hero_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItem) Reset() {
	*x = FeedItem{}
	mi := &file_feeds_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItem) ProtoMessage() {}

func (x *FeedItem) ProtoReflect() protoreflect.Message {
	mi := &file_feeds_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItem.ProtoReflect.Descriptor instead.
func (*FeedItem) Descriptor() ([]byte, []int) {
	return file_feeds_proto_rawDescGZIP(), []int{14}
}

func (x *FeedItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeedItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FeedItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FeedItem) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *FeedItem) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *FeedItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FeedItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FeedItem) GetHeroImage() string {
	if x != nil {
		return x.HeroImage
	}
	return ""
}

// FeedResult represents the result of fetching a feed
type FeedResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feed          *Feed                  `protobuf:"bytes,1,opt,name=feed,proto3" json:"feed,omitempty"`
	Items         []*FeedItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedResult) Reset() {
	*x = FeedResult{}
	mi := &file_feeds_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedResult) ProtoMessage() {}

func (x *FeedResult) ProtoReflect() protoreflect.Message {
	mi := &file_feeds_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedResult.ProtoReflect.Descriptor instead.
func (*FeedResult) Descriptor() ([]byte, []int) {
	return file_feeds_proto_rawDescGZIP(), []int{15}
}

func (x *FeedResult) GetFeed() *Feed {
	if x != nil {
		return x.Feed
	}
	return nil
}

func (x *FeedResult) GetItems() []*FeedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *FeedResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_feeds_proto protoreflect.FileDescriptor

const file_feeds_proto_rawDesc = "" +
	"\n" +
	"\vfeeds.proto\x12\bdownlink\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\x1a\x0earticles.proto\x1a\fconfig.proto\"\x12\n" +
	"\x10ListFeedsRequest\"9\n" +
	"\x11ListFeedsResponse\x12$\n" +
	"\x05feeds\x18\x01 \x03(\v2\x0e.downlink.FeedR\x05feeds\"L\n" +
	"\x13RegisterFeedRequest\x125\n" +
	"\vfeed_config\x18\x01 \x01(\v2\x14.downlink.FeedConfigR\n" +
	"feedConfig\"\x18\n" +
	"\x16RefreshAllFeedsRequest\"\xbc\x01\n" +
	"\x13RefreshFeedResponse\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\tR\x06feedId\x12\x1d\n" +
	"\n" +
	"feed_title\x18\x02 \x01(\tR\tfeedTitle\x12#\n" +
	"\rtotal_fetched\x18\x03 \x01(\x05R\ftotalFetched\x12\x16\n" +
	"\x06stored\x18\x04 \x01(\x05R\x06stored\x12\x18\n" +
	"\askipped\x18\x05 \x01(\x05R\askipped\x12\x16\n" +
	"\x06errors\x18\x06 \x03(\tR\x06errors\"\xbc\x01\n" +
	"\x14RefreshAllFeedsEvent\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.downlink.RefreshFeedResponseR\x06result\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\x05R\tcompleted\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x129\n" +
	"\n" +
	"event_type\x18\x04 \x01(\x0e2\x1a.downlink.RefreshEventTypeR\teventType\"\xc1\x01\n" +
	"\x12RefreshFeedRequest\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\tR\x06feedId\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x1c\n" +
	"\toverwrite\x18\x04 \x01(\bR\toverwrite\x12\x18\n" +
	"\arestore\x18\x05 \x01(\bR\arestore\",\n" +
	"\x11DeleteFeedRequest\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\tR\x06feedId\"\x9a\x01\n" +
	"\x11ApplyFeedsRequest\x12*\n" +
	"\x05feeds\x18\x01 \x03(\v2\x14.downlink.FeedConfigR\x05feeds\x12@\n" +
	"\x11default_selectors\x18\x02 \x01(\v2\x13.downlink.SelectorsR\x10defaultSelectors\x12\x17\n" +
	"\adry_run\x18\x03 \x01(\bR\x06dryRun\"d\n" +
	"\x12ApplyFeedsResponse\x12\x18\n" +
	"\acreated\x18\x01 \x03(\tR\acreated\x12\x18\n" +
	"\aupdated\x18\x02 \x03(\tR\aupdated\x12\x1a\n" +
	"\bdisabled\x18\x03 \x03(\tR\bdisabled\"H\n" +
	"\x12DeleteFeedsRequest\x12\x19\n" +
	"\bfeed_ids\x18\x01 \x03(\tR\afeedIds\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\"L\n" +
	"\x13DeleteFeedsResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x03(\tR\adeleted\x12\x1b\n" +
	"\tnot_found\x18\x02 \x03(\tR\bnotFound\"\x88\x01\n" +
	"\tFeedGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\x12$\n" +
	"\x05feeds\x18\x05 \x03(\v2\x0e.downlink.FeedR\x05feeds\"\xfa\x02\n" +
	"\x04Feed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x129\n" +
	"\n" +
	"last_fetch\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tlastFetch\x125\n" +
	"\ascraper\x18\x06 \x03(\v2\x1b.downlink.Feed.ScraperEntryR\ascraper\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x12\x19\n" +
	"\bgroup_id\x18\b \x01(\tR\agroupId\x12-\n" +
	"\barticles\x18\t \x03(\v2\x11.downlink.ArticleR\barticles\x1aP\n" +
	"\fScraperEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\xec\x01\n" +
	"\bFeedItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04link\x18\x04 \x01(\tR\x04link\x12=\n" +
	"\fpublished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"hero_image\x18\b \x01(\tR\theroImage\"p\n" +
	"\n" +
	"FeedResult\x12\"\n" +
	"\x04feed\x18\x01 \x01(\v2\x0e.downlink.FeedR\x04feed\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.downlink.FeedItemR\x05items\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*.\n" +
	"\x10RefreshEventType\x12\v\n" +
	"\aSTARTED\x10\x00\x12\r\n" +
	"\tCOMPLETED\x10\x012\xa4\x04\n" +
	"\fFeedsService\x12F\n" +
	"\tListFeeds\x12\x1a.downlink.ListFeedsRequest\x1a\x1b.downlink.ListFeedsResponse\"\x00\x12G\n" +
	"\fRegisterFeed\x12\x1d.downlink.RegisterFeedRequest\x1a\x16.google.protobuf.Empty\"\x00\x12W\n" +
	"\x0fRefreshAllFeeds\x12 .downlink.RefreshAllFeedsRequest\x1a\x1e.downlink.RefreshAllFeedsEvent\"\x000\x01\x12L\n" +
	"\vRefreshFeed\x12\x1c.downlink.RefreshFeedRequest\x1a\x1d.downlink.RefreshFeedResponse\"\x00\x12C\n" +
	"\n" +
	"DeleteFeed\x12\x1b.downlink.DeleteFeedRequest\x1a\x16.google.protobuf.Empty\"\x00\x12I\n" +
	"\n" +
	"ApplyFeeds\x12\x1b.downlink.ApplyFeedsRequest\x1a\x1c.downlink.ApplyFeedsResponse\"\x00\x12L\n" +
	"\vDeleteFeeds\x12\x1c.downlink.DeleteFeedsRequest\x1a\x1d.downlink.DeleteFeedsResponse\"\x00B\tZ\aprotos/b\x06proto3"

var (
	file_feeds_proto_rawDescOnce sync.Once
	file_feeds_proto_rawDescData []byte
)

func file_feeds_proto_rawDescGZIP() []byte {
	file_feeds_proto_rawDescOnce.Do(func() {
		file_feeds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feeds_proto_rawDesc), len(file_feeds_proto_rawDesc)))
	})
	return file_feeds_proto_rawDescData
}

var file_feeds_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_feeds_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_feeds_proto_goTypes = []any{
	(RefreshEventType)(0),          // 0: downlink.RefreshEventType
	(*ListFeedsRequest)(nil),       // 1: downlink.ListFeedsRequest
	(*ListFeedsResponse)(nil),      // 2: downlink.ListFeedsResponse
	(*RegisterFeedRequest)(nil),    // 3: downlink.RegisterFeedRequest
	(*RefreshAllFeedsRequest)(nil), // 4: downlink.RefreshAllFeedsRequest
	(*RefreshFeedResponse)(nil),    // 5: downlink.RefreshFeedResponse
	(*RefreshAllFeedsEvent)(nil),   // 6: downlink.RefreshAllFeedsEvent
	(*RefreshFeedRequest)(nil),     // 7: downlink.RefreshFeedRequest
	(*DeleteFeedRequest)(nil),      // 8: downlink.DeleteFeedRequest
	(*ApplyFeedsRequest)(nil),      // 9: downlink.ApplyFeedsRequest
	(*ApplyFeedsResponse)(nil),     // 10: downlink.ApplyFeedsResponse
	(*DeleteFeedsRequest)(nil),     // 11: downlink.DeleteFeedsRequest
	(*DeleteFeedsResponse)(nil),    // 12: downlink.DeleteFeedsResponse
	(*FeedGroup)(nil),              // 13: downlink.FeedGroup
	(*Feed)(nil),                   // 14: downlink.Feed
	(*FeedItem)(nil),               // 15: downlink.FeedItem
	(*FeedResult)(nil),             // 16: downlink.FeedResult
	nil,                            // 17: downlink.Feed.ScraperEntry
	(*FeedConfig)(nil),             // 18: downlink.FeedConfig
	(*timestamppb.Timestamp)(nil),  // 19: google.protobuf.Timestamp
	(*Selectors)(nil),              // 20: downlink.Selectors
	(*Article)(nil),                // 21: downlink.Article
	(*anypb.Any)(nil),              // 22: google.protobuf.Any
	(*emptypb.Empty)(nil),          // 23: google.protobuf.Empty
}
var file_feeds_proto_depIdxs = []int32{
	14, // 0: downlink.ListFeedsResponse.feeds:type_name -> downlink.Feed
	18, // 1: downlink.RegisterFeedRequest.feed_config:type_name -> downlink.FeedConfig
	5,  // 2: downlink.RefreshAllFeedsEvent.result:type_name -> downlink.RefreshFeedResponse
	0,  // 3: downlink.RefreshAllFeedsEvent.event_type:type_name -> downlink.RefreshEventType
	19, // 4: downlink.RefreshFeedRequest.from:type_name -> google.protobuf.Timestamp
	19, // 5: downlink.RefreshFeedRequest.to:type_name -> google.protobuf.Timestamp
	18, // 6: downlink.ApplyFeedsRequest.feeds:type_name -> downlink.FeedConfig
	20, // 7: downlink.ApplyFeedsRequest.default_selectors:type_name -> downlink.Selectors
	14, // 8: downlink.FeedGroup.feeds:type_name -> downlink.Feed
	19, // 9: downlink.Feed.last_fetch:type_name -> google.protobuf.Timestamp
	17, // 10: downlink.Feed.scraper:type_name -> downlink.Feed.ScraperEntry
	21, // 11: downlink.Feed.articles:type_name -> downlink.Article
	19, // 12: downlink.FeedItem.published_at:type_name -> google.protobuf.Timestamp
	14, // 13: downlink.FeedResult.feed:type_name -> downlink.Feed
	15, // 14: downlink.FeedResult.items:type_name -> downlink.FeedItem
	22, // 15: downlink.Feed.ScraperEntry.value:type_name -> google.protobuf.Any
	1,  // 16: downlink.FeedsService.ListFeeds:input_type -> downlink.ListFeedsRequest
	3,  // 17: downlink.FeedsService.RegisterFeed:input_type -> downlink.RegisterFeedRequest
	4,  // 18: downlink.FeedsService.RefreshAllFeeds:input_type -> downlink.RefreshAllFeedsRequest
	7,  // 19: downlink.FeedsService.RefreshFeed:input_type -> downlink.RefreshFeedRequest
	8,  // 20: downlink.FeedsService.DeleteFeed:input_type -> downlink.DeleteFeedRequest
	9,  // 21: downlink.FeedsService.ApplyFeeds:input_type -> downlink.ApplyFeedsRequest
	11, // 22: downlink.FeedsService.DeleteFeeds:input_type -> downlink.DeleteFeedsRequest
	2,  // 23: downlink.FeedsService.ListFeeds:output_type -> downlink.ListFeedsResponse
	23, // 24: downlink.FeedsService.RegisterFeed:output_type -> google.protobuf.Empty
	6,  // 25: downlink.FeedsService.RefreshAllFeeds:output_type -> downlink.RefreshAllFeedsEvent
	5,  // 26: downlink.FeedsService.RefreshFeed:output_type -> downlink.RefreshFeedResponse
	23, // 27: downlink.FeedsService.DeleteFeed:output_type -> google.protobuf.Empty
	10, // 28: downlink.FeedsService.ApplyFeeds:output_type -> downlink.ApplyFeedsResponse
	12, // 29: downlink.FeedsService.DeleteFeeds:output_type -> downlink.DeleteFeedsResponse
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_feeds_proto_init() }
func file_feeds_proto_init() {
	if File_feeds_proto != nil {
		return
	}
	file_articles_proto_init()
	file_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feeds_proto_rawDesc), len(file_feeds_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feeds_proto_goTypes,
		DependencyIndexes: file_feeds_proto_depIdxs,
		EnumInfos:         file_feeds_proto_enumTypes,
		MessageInfos:      file_feeds_proto_msgTypes,
	}.Build()
	File_feeds_proto = out.File
	file_feeds_proto_goTypes = nil
	file_feeds_proto_depIdxs = nil
}
