// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: llms.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetAnalysisConfigRequest is the request for the GetAnalysisConfig method
type GetAnalysisConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalysisConfigRequest) Reset() {
	*x = GetAnalysisConfigRequest{}
	mi := &file_llms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisConfigRequest) ProtoMessage() {}

func (x *GetAnalysisConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisConfigRequest.ProtoReflect.Descriptor instead.
func (*GetAnalysisConfigRequest) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{0}
}

// GetAnalysisConfigResponse is the response for the GetAnalysisConfig method
type GetAnalysisConfigResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AnalysisConfig *AnalysisConfig        `protobuf:"bytes,1,opt,name=analysis_config,json=analysisConfig,proto3" json:"analysis_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAnalysisConfigResponse) Reset() {
	*x = GetAnalysisConfigResponse{}
	mi := &file_llms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisConfigResponse) ProtoMessage() {}

func (x *GetAnalysisConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisConfigResponse.ProtoReflect.Descriptor instead.
func (*GetAnalysisConfigResponse) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{1}
}

func (x *GetAnalysisConfigResponse) GetAnalysisConfig() *AnalysisConfig {
	if x != nil {
		return x.AnalysisConfig
	}
	return nil
}

// GetLLMProvidersRequest is the request for the GetLLMProviders method
type GetLLMProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLLMProvidersRequest) Reset() {
	*x = GetLLMProvidersRequest{}
	mi := &file_llms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLLMProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLLMProvidersRequest) ProtoMessage() {}

func (x *GetLLMProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLLMProvidersRequest.ProtoReflect.Descriptor instead.
func (*GetLLMProvidersRequest) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{2}
}

// GetLLMProvidersResponse is the response for the GetLLMProviders method
type GetLLMProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ProviderConfig      `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLLMProvidersResponse) Reset() {
	*x = GetLLMProvidersResponse{}
	mi := &file_llms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLLMProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLLMProvidersResponse) ProtoMessage() {}

func (x *GetLLMProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLLMProvidersResponse.ProtoReflect.Descriptor instead.
func (*GetLLMProvidersResponse) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{3}
}

func (x *GetLLMProvidersResponse) GetProviders() []*ProviderConfig {
	if x != nil {
		return x.Providers
	}
	return nil
}

// SaveLLMProvidersRequest is the request for the SaveLLMProviders method
type SaveLLMProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ProviderConfig      `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveLLMProvidersRequest) Reset() {
	*x = SaveLLMProvidersRequest{}
	mi := &file_llms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveLLMProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLLMProvidersRequest) ProtoMessage() {}

func (x *SaveLLMProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLLMProvidersRequest.ProtoReflect.Descriptor instead.
func (*SaveLLMProvidersRequest) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{4}
}

func (x *SaveLLMProvidersRequest) GetProviders() []*ProviderConfig {
	if x != nil {
		return x.Providers
	}
	return nil
}

// GetAvailableModelsRequest is the request for the GetAvailableModels method
type GetAvailableModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableModelsRequest) Reset() {
	*x = GetAvailableModelsRequest{}
	mi := &file_llms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableModelsRequest) ProtoMessage() {}

func (x *GetAvailableModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableModelsRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableModelsRequest) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{5}
}

// ModelInfo represents generic model information
type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ProviderType  string                 `protobuf:"bytes,5,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_llms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{6}
}

func (x *ModelInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ModelInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModelInfo) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

// AnalyzeArticleWithProviderModelRequest is the request for the AnalyzeArticleWithProviderModel method
type AnalyzeArticleWithProviderModelRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ArticleId      string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	ProviderType   string                 `protobuf:"bytes,2,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	ModelName      string                 `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	FastMode       bool                   `protobuf:"varint,4,opt,name=fast_mode,json=fastMode,proto3" json:"fast_mode,omitempty"`                   // If true, only extract key points
	SkipCategorize bool                   `protobuf:"varint,5,opt,name=skip_categorize,json=skipCategorize,proto3" json:"skip_categorize,omitempty"` // If true, skip the categorize (category + tags) task
	ProviderName   string                 `protobuf:"bytes,6,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`        // Named profile from config.providers; takes precedence over provider_type/model_name
	SkipReferences bool                   `protobuf:"varint,7,opt,name=skip_references,json=skipReferences,proto3" json:"skip_references,omitempty"` // If true, skip the referenced_reports task
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeArticleWithProviderModelRequest) Reset() {
	*x = AnalyzeArticleWithProviderModelRequest{}
	mi := &file_llms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeArticleWithProviderModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeArticleWithProviderModelRequest) ProtoMessage() {}

func (x *AnalyzeArticleWithProviderModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeArticleWithProviderModelRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeArticleWithProviderModelRequest) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{7}
}

func (x *AnalyzeArticleWithProviderModelRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *AnalyzeArticleWithProviderModelRequest) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *AnalyzeArticleWithProviderModelRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *AnalyzeArticleWithProviderModelRequest) GetFastMode() bool {
	if x != nil {
		return x.FastMode
	}
	return false
}

func (x *AnalyzeArticleWithProviderModelRequest) GetSkipCategorize() bool {
	if x != nil {
		return x.SkipCategorize
	}
	return false
}

func (x *AnalyzeArticleWithProviderModelRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *AnalyzeArticleWithProviderModelRequest) GetSkipReferences() bool {
	if x != nil {
		return x.SkipReferences
	}
	return false
}

// AnalyzeArticleWithProviderModelResponse is the response for the AnalyzeArticleWithProviderModel method
type AnalyzeArticleWithProviderModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analysis      *ArticleAnalysis       `protobuf:"bytes,1,opt,name=analysis,proto3" json:"analysis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeArticleWithProviderModelResponse) Reset() {
	*x = AnalyzeArticleWithProviderModelResponse{}
	mi := &file_llms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeArticleWithProviderModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeArticleWithProviderModelResponse) ProtoMessage() {}

func (x *AnalyzeArticleWithProviderModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeArticleWithProviderModelResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeArticleWithProviderModelResponse) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{8}
}

func (x *AnalyzeArticleWithProviderModelResponse) GetAnalysis() *ArticleAnalysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

// AnalyzeArticleRequest is the request for the AnalyzeArticle method
type AnalyzeArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	FastMode      bool                   `protobuf:"varint,2,opt,name=fast_mode,json=fastMode,proto3" json:"fast_mode,omitempty"` // If true, only extract key points
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeArticleRequest) Reset() {
	*x = AnalyzeArticleRequest{}
	mi := &file_llms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeArticleRequest) ProtoMessage() {}

func (x *AnalyzeArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeArticleRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeArticleRequest) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{9}
}

func (x *AnalyzeArticleRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *AnalyzeArticleRequest) GetFastMode() bool {
	if x != nil {
		return x.FastMode
	}
	return false
}

// AnalyzeArticleResponse is the response for the AnalyzeArticle method
type AnalyzeArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analysis      *ArticleAnalysis       `protobuf:"bytes,1,opt,name=analysis,proto3" json:"analysis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeArticleResponse) Reset() {
	*x = AnalyzeArticleResponse{}
	mi := &file_llms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeArticleResponse) ProtoMessage() {}

func (x *AnalyzeArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeArticleResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeArticleResponse) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{10}
}

func (x *AnalyzeArticleResponse) GetAnalysis() *ArticleAnalysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

// PreviewAnalysisPromptRequest is the request for the PreviewAnalysisPrompt method
type PreviewAnalysisPromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	ProviderType  string                 `protobuf:"bytes,2,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	ModelName     string                 `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewAnalysisPromptRequest) Reset() {
	*x = PreviewAnalysisPromptRequest{}
	mi := &file_llms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewAnalysisPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewAnalysisPromptRequest) ProtoMessage() {}

func (x *PreviewAnalysisPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewAnalysisPromptRequest.ProtoReflect.Descriptor instead.
func (*PreviewAnalysisPromptRequest) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{11}
}

func (x *PreviewAnalysisPromptRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *PreviewAnalysisPromptRequest) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *PreviewAnalysisPromptRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

// PreviewAnalysisPromptResponse is the response for the PreviewAnalysisPrompt method
type PreviewAnalysisPromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewAnalysisPromptResponse) Reset() {
	*x = PreviewAnalysisPromptResponse{}
	mi := &file_llms_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewAnalysisPromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewAnalysisPromptResponse) ProtoMessage() {}

func (x *PreviewAnalysisPromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewAnalysisPromptResponse.ProtoReflect.Descriptor instead.
func (*PreviewAnalysisPromptResponse) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{12}
}

func (x *PreviewAnalysisPromptResponse) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

// AnalysisProgressEvent is streamed during article analysis to report task-level progress
type AnalysisProgressEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which task: "categorize", "key_points", "tags", "importance", "insights", "summaries"
	TaskName string `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	// Status: "started", "completed", "error", "token"
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// 1-based index of the current task
	TaskIndex int32 `protobuf:"varint,3,opt,name=task_index,json=taskIndex,proto3" json:"task_index,omitempty"`
	// Total number of tasks for this analysis
	TotalTasks int32 `protobuf:"varint,4,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	// The parsed JSON result for this task (only on "completed")
	TaskResult string `protobuf:"bytes,5,opt,name=task_result,json=taskResult,proto3" json:"task_result,omitempty"`
	// Error message (only on "error")
	Error string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// Final analysis (only on the last "completed" event)
	Analysis *ArticleAnalysis `protobuf:"bytes,7,opt,name=analysis,proto3" json:"analysis,omitempty"`
	// Token text chunk during LLM streaming (only on "token" status events)
	TokenChunk    string `protobuf:"bytes,8,opt,name=token_chunk,json=tokenChunk,proto3" json:"token_chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisProgressEvent) Reset() {
	*x = AnalysisProgressEvent{}
	mi := &file_llms_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisProgressEvent) ProtoMessage() {}

func (x *AnalysisProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisProgressEvent.ProtoReflect.Descriptor instead.
func (*AnalysisProgressEvent) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{13}
}

func (x *AnalysisProgressEvent) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *AnalysisProgressEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnalysisProgressEvent) GetTaskIndex() int32 {
	if x != nil {
		return x.TaskIndex
	}
	return 0
}

func (x *AnalysisProgressEvent) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *AnalysisProgressEvent) GetTaskResult() string {
	if x != nil {
		return x.TaskResult
	}
	return ""
}

func (x *AnalysisProgressEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AnalysisProgressEvent) GetAnalysis() *ArticleAnalysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

func (x *AnalysisProgressEvent) GetTokenChunk() string {
	if x != nil {
		return x.TokenChunk
	}
	return ""
}

// GenericLLMRequest represents a generic request to an LLM provider
type GenericLLMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Temperature   float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericLLMRequest) Reset() {
	*x = GenericLLMRequest{}
	mi := &file_llms_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericLLMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericLLMRequest) ProtoMessage() {}

func (x *GenericLLMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericLLMRequest.ProtoReflect.Descriptor instead.
func (*GenericLLMRequest) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{14}
}

func (x *GenericLLMRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenericLLMRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GenericLLMRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenericLLMRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GenericLLMRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

// Message represents a message in a chat-based LLM request
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_llms_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{15}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// OllamaRequest represents the request to the Ollama API
type OllamaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Stream        bool                   `protobuf:"varint,3,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OllamaRequest) Reset() {
	*x = OllamaRequest{}
	mi := &file_llms_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OllamaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OllamaRequest) ProtoMessage() {}

func (x *OllamaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OllamaRequest.ProtoReflect.Descriptor instead.
func (*OllamaRequest) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{16}
}

func (x *OllamaRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *OllamaRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *OllamaRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

// OllamaResponse represents the response from the Ollama API
type OllamaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OllamaResponse) Reset() {
	*x = OllamaResponse{}
	mi := &file_llms_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OllamaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OllamaResponse) ProtoMessage() {}

func (x *OllamaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OllamaResponse.ProtoReflect.Descriptor instead.
func (*OllamaResponse) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{17}
}

func (x *OllamaResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *OllamaResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *OllamaResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// OpenAIRequest represents a request to the OpenAI API
type OpenAIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Temperature   float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAIRequest) Reset() {
	*x = OpenAIRequest{}
	mi := &file_llms_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAIRequest) ProtoMessage() {}

func (x *OpenAIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAIRequest.ProtoReflect.Descriptor instead.
func (*OpenAIRequest) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{18}
}

func (x *OpenAIRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *OpenAIRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *OpenAIRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *OpenAIRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

// OpenAIChoice represents a choice in the OpenAI API response
type OpenAIChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Message       *Message               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FinishReason  string                 `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAIChoice) Reset() {
	*x = OpenAIChoice{}
	mi := &file_llms_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAIChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAIChoice) ProtoMessage() {}

func (x *OpenAIChoice) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAIChoice.ProtoReflect.Descriptor instead.
func (*OpenAIChoice) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{19}
}

func (x *OpenAIChoice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *OpenAIChoice) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *OpenAIChoice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

// OpenAIResponse represents a response from the OpenAI API
type OpenAIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Object        string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Created       int64                  `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Choices       []*OpenAIChoice        `protobuf:"bytes,5,rep,name=choices,proto3" json:"choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAIResponse) Reset() {
	*x = OpenAIResponse{}
	mi := &file_llms_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAIResponse) ProtoMessage() {}

func (x *OpenAIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAIResponse.ProtoReflect.Descriptor instead.
func (*OpenAIResponse) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{20}
}

func (x *OpenAIResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OpenAIResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *OpenAIResponse) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *OpenAIResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *OpenAIResponse) GetChoices() []*OpenAIChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

// AnthropicRequest represents a request to the Anthropic API
type AnthropicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Temperature   float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnthropicRequest) Reset() {
	*x = AnthropicRequest{}
	mi := &file_llms_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnthropicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnthropicRequest) ProtoMessage() {}

func (x *AnthropicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnthropicRequest.ProtoReflect.Descriptor instead.
func (*AnthropicRequest) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{21}
}

func (x *AnthropicRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AnthropicRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *AnthropicRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *AnthropicRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

// AnthropicContentItem represents a content item in the Anthropic API response
type AnthropicContentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnthropicContentItem) Reset() {
	*x = AnthropicContentItem{}
	mi := &file_llms_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnthropicContentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnthropicContentItem) ProtoMessage() {}

func (x *AnthropicContentItem) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnthropicContentItem.ProtoReflect.Descriptor instead.
func (*AnthropicContentItem) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{22}
}

func (x *AnthropicContentItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AnthropicContentItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// AnthropicResponse represents a response from the Anthropic API
type AnthropicResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Model         string                  `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Content       []*AnthropicContentItem `protobuf:"bytes,4,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnthropicResponse) Reset() {
	*x = AnthropicResponse{}
	mi := &file_llms_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnthropicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnthropicResponse) ProtoMessage() {}

func (x *AnthropicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnthropicResponse.ProtoReflect.Descriptor instead.
func (*AnthropicResponse) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{23}
}

func (x *AnthropicResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnthropicResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AnthropicResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AnthropicResponse) GetContent() []*AnthropicContentItem {
	if x != nil {
		return x.Content
	}
	return nil
}

// ModelsResponse represents the response structure for GetAvailableModels
type ModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelsResponse) Reset() {
	*x = ModelsResponse{}
	mi := &file_llms_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelsResponse) ProtoMessage() {}

func (x *ModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelsResponse.ProtoReflect.Descriptor instead.
func (*ModelsResponse) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{24}
}

func (x *ModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ModelsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// OpenAIModelData represents a model in OpenAI's models endpoint response
type OpenAIModelData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Object        string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Created       int64                  `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	OwnedBy       string                 `protobuf:"bytes,4,opt,name=owned_by,json=ownedBy,proto3" json:"owned_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAIModelData) Reset() {
	*x = OpenAIModelData{}
	mi := &file_llms_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAIModelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAIModelData) ProtoMessage() {}

func (x *OpenAIModelData) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAIModelData.ProtoReflect.Descriptor instead.
func (*OpenAIModelData) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{25}
}

func (x *OpenAIModelData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OpenAIModelData) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *OpenAIModelData) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *OpenAIModelData) GetOwnedBy() string {
	if x != nil {
		return x.OwnedBy
	}
	return ""
}

// OpenAIModelsResponse represents the response from OpenAI's models endpoint
type OpenAIModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        string                 `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Data          []*OpenAIModelData     `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAIModelsResponse) Reset() {
	*x = OpenAIModelsResponse{}
	mi := &file_llms_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAIModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAIModelsResponse) ProtoMessage() {}

func (x *OpenAIModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAIModelsResponse.ProtoReflect.Descriptor instead.
func (*OpenAIModelsResponse) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{26}
}

func (x *OpenAIModelsResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *OpenAIModelsResponse) GetData() []*OpenAIModelData {
	if x != nil {
		return x.Data
	}
	return nil
}

// AnthropicModelData represents a model in Anthropic's models endpoint response
type AnthropicModelData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnthropicModelData) Reset() {
	*x = AnthropicModelData{}
	mi := &file_llms_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnthropicModelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnthropicModelData) ProtoMessage() {}

func (x *AnthropicModelData) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnthropicModelData.ProtoReflect.Descriptor instead.
func (*AnthropicModelData) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{27}
}

func (x *AnthropicModelData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AnthropicModelData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnthropicModelData) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AnthropicModelData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// AnthropicModelsResponse represents the response from Anthropic's models endpoint
type AnthropicModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*AnthropicModelData  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	FirstId       string                 `protobuf:"bytes,3,opt,name=first_id,json=firstId,proto3" json:"first_id,omitempty"`
	LastId        string                 `protobuf:"bytes,4,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnthropicModelsResponse) Reset() {
	*x = AnthropicModelsResponse{}
	mi := &file_llms_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnthropicModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnthropicModelsResponse) ProtoMessage() {}

func (x *AnthropicModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnthropicModelsResponse.ProtoReflect.Descriptor instead.
func (*AnthropicModelsResponse) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{28}
}

func (x *AnthropicModelsResponse) GetData() []*AnthropicModelData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AnthropicModelsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *AnthropicModelsResponse) GetFirstId() string {
	if x != nil {
		return x.FirstId
	}
	return ""
}

func (x *AnthropicModelsResponse) GetLastId() string {
	if x != nil {
		return x.LastId
	}
	return ""
}

// OllamaModelDetails represents the details of an Ollama model
type OllamaModelDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ParentModel       string                 `protobuf:"bytes,1,opt,name=parent_model,json=parentModel,proto3" json:"parent_model,omitempty"`
	Format            string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Family            string                 `protobuf:"bytes,3,opt,name=family,proto3" json:"family,omitempty"`
	Families          []string               `protobuf:"bytes,4,rep,name=families,proto3" json:"families,omitempty"`
	ParameterSize     string                 `protobuf:"bytes,5,opt,name=parameter_size,json=parameterSize,proto3" json:"parameter_size,omitempty"`
	QuantizationLevel string                 `protobuf:"bytes,6,opt,name=quantization_level,json=quantizationLevel,proto3" json:"quantization_level,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OllamaModelDetails) Reset() {
	*x = OllamaModelDetails{}
	mi := &file_llms_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OllamaModelDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OllamaModelDetails) ProtoMessage() {}

func (x *OllamaModelDetails) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OllamaModelDetails.ProtoReflect.Descriptor instead.
func (*OllamaModelDetails) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{29}
}

func (x *OllamaModelDetails) GetParentModel() string {
	if x != nil {
		return x.ParentModel
	}
	return ""
}

func (x *OllamaModelDetails) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *OllamaModelDetails) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *OllamaModelDetails) GetFamilies() []string {
	if x != nil {
		return x.Families
	}
	return nil
}

func (x *OllamaModelDetails) GetParameterSize() string {
	if x != nil {
		return x.ParameterSize
	}
	return ""
}

func (x *OllamaModelDetails) GetQuantizationLevel() string {
	if x != nil {
		return x.QuantizationLevel
	}
	return ""
}

// OllamaModelData represents a model in Ollama's models endpoint response
type OllamaModelData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	ModifiedAt    string                 `protobuf:"bytes,3,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Digest        string                 `protobuf:"bytes,5,opt,name=digest,proto3" json:"digest,omitempty"`
	Details       *OllamaModelDetails    `protobuf:"bytes,6,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OllamaModelData) Reset() {
	*x = OllamaModelData{}
	mi := &file_llms_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OllamaModelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OllamaModelData) ProtoMessage() {}

func (x *OllamaModelData) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OllamaModelData.ProtoReflect.Descriptor instead.
func (*OllamaModelData) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{30}
}

func (x *OllamaModelData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OllamaModelData) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *OllamaModelData) GetModifiedAt() string {
	if x != nil {
		return x.ModifiedAt
	}
	return ""
}

func (x *OllamaModelData) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *OllamaModelData) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *OllamaModelData) GetDetails() *OllamaModelDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

// OllamaModelsResponse represents the response from Ollama's models endpoint
type OllamaModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*OllamaModelData     `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OllamaModelsResponse) Reset() {
	*x = OllamaModelsResponse{}
	mi := &file_llms_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OllamaModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OllamaModelsResponse) ProtoMessage() {}

func (x *OllamaModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llms_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OllamaModelsResponse.ProtoReflect.Descriptor instead.
func (*OllamaModelsResponse) Descriptor() ([]byte, []int) {
	return file_llms_proto_rawDescGZIP(), []int{31}
}

func (x *OllamaModelsResponse) GetModels() []*OllamaModelData {
	if x != nil {
		return x.Models
	}
	return nil
}

var File_llms_proto protoreflect.FileDescriptor

const file_llms_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"llms.proto\x12\bdownlink\x1a\x1bgoogle/protobuf/empty.proto\x1a\fconfig.proto\x1a\x0eanalysis.proto\"\x1a\n" +
	"\x18GetAnalysisConfigRequest\"^\n" +
	"\x19GetAnalysisConfigResponse\x12A\n" +
	"\x0fanalysis_config\x18\x01 \x01(\v2\x18.downlink.AnalysisConfigR\x0eanalysisConfig\"\x18\n" +
	"\x16GetLLMProvidersRequest\"Q\n" +
	"\x17GetLLMProvidersResponse\x126\n" +
	"\tproviders\x18\x01 \x03(\v2\x18.downlink.ProviderConfigR\tproviders\"Q\n" +
	"\x17SaveLLMProvidersRequest\x126\n" +
	"\tproviders\x18\x01 \x03(\v2\x18.downlink.ProviderConfigR\tproviders\"\x1b\n" +
	"\x19GetAvailableModelsRequest\"\x99\x01\n" +
	"\tModelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rprovider_type\x18\x05 \x01(\tR\fproviderType\"\x9f\x02\n" +
	"&AnalyzeArticleWithProviderModelRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12#\n" +
	"\rprovider_type\x18\x02 \x01(\tR\fproviderType\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12\x1b\n" +
	"\tfast_mode\x18\x04 \x01(\bR\bfastMode\x12'\n" +
	"\x0fskip_categorize\x18\x05 \x01(\bR\x0eskipCategorize\x12#\n" +
	"\rprovider_name\x18\x06 \x01(\tR\fproviderName\x12'\n" +
	"\x0fskip_references\x18\a \x01(\bR\x0eskipReferences\"`\n" +
	"'AnalyzeArticleWithProviderModelResponse\x125\n" +
	"\banalysis\x18\x01 \x01(\v2\x19.downlink.ArticleAnalysisR\banalysis\"S\n" +
	"\x15AnalyzeArticleRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x1b\n" +
	"\tfast_mode\x18\x02 \x01(\bR\bfastMode\"O\n" +
	"\x16AnalyzeArticleResponse\x125\n" +
	"\banalysis\x18\x01 \x01(\v2\x19.downlink.ArticleAnalysisR\banalysis\"\x81\x01\n" +
	"\x1cPreviewAnalysisPromptRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12#\n" +
	"\rprovider_type\x18\x02 \x01(\tR\fproviderType\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\"7\n" +
	"\x1dPreviewAnalysisPromptResponse\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"\x9b\x02\n" +
	"\x15AnalysisProgressEvent\x12\x1b\n" +
	"\ttask_name\x18\x01 \x01(\tR\btaskName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"task_index\x18\x03 \x01(\x05R\ttaskIndex\x12\x1f\n" +
	"\vtotal_tasks\x18\x04 \x01(\x05R\n" +
	"totalTasks\x12\x1f\n" +
	"\vtask_result\x18\x05 \x01(\tR\n" +
	"taskResult\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x125\n" +
	"\banalysis\x18\a \x01(\v2\x19.downlink.ArticleAnalysisR\banalysis\x12\x1f\n" +
	"\vtoken_chunk\x18\b \x01(\tR\n" +
	"tokenChunk\"\xb1\x01\n" +
	"\x11GenericLLMRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12-\n" +
	"\bmessages\x18\x02 \x03(\v2\x11.downlink.MessageR\bmessages\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"U\n" +
	"\rOllamaRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\bR\x06stream\"a\n" +
	"\x0eOllamaResponse\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"\x95\x01\n" +
	"\rOpenAIRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12-\n" +
	"\bmessages\x18\x02 \x03(\v2\x11.downlink.MessageR\bmessages\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\"v\n" +
	"\fOpenAIChoice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12+\n" +
	"\amessage\x18\x02 \x01(\v2\x11.downlink.MessageR\amessage\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\"\x9a\x01\n" +
	"\x0eOpenAIResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x120\n" +
	"\achoices\x18\x05 \x03(\v2\x16.downlink.OpenAIChoiceR\achoices\"\x98\x01\n" +
	"\x10AnthropicRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12-\n" +
	"\bmessages\x18\x02 \x03(\v2\x11.downlink.MessageR\bmessages\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\">\n" +
	"\x14AnthropicContentItem\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x87\x01\n" +
	"\x11AnthropicResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x128\n" +
	"\acontent\x18\x04 \x03(\v2\x1e.downlink.AnthropicContentItemR\acontent\"S\n" +
	"\x0eModelsResponse\x12+\n" +
	"\x06models\x18\x01 \x03(\v2\x13.downlink.ModelInfoR\x06models\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"n\n" +
	"\x0fOpenAIModelData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x19\n" +
	"\bowned_by\x18\x04 \x01(\tR\aownedBy\"]\n" +
	"\x14OpenAIModelsResponse\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12-\n" +
	"\x04data\x18\x02 \x03(\v2\x19.downlink.OpenAIModelDataR\x04data\"z\n" +
	"\x12AnthropicModelData\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"\x9a\x01\n" +
	"\x17AnthropicModelsResponse\x120\n" +
	"\x04data\x18\x01 \x03(\v2\x1c.downlink.AnthropicModelDataR\x04data\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x19\n" +
	"\bfirst_id\x18\x03 \x01(\tR\afirstId\x12\x17\n" +
	"\alast_id\x18\x04 \x01(\tR\x06lastId\"\xd9\x01\n" +
	"\x12OllamaModelDetails\x12!\n" +
	"\fparent_model\x18\x01 \x01(\tR\vparentModel\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x16\n" +
	"\x06family\x18\x03 \x01(\tR\x06family\x12\x1a\n" +
	"\bfamilies\x18\x04 \x03(\tR\bfamilies\x12%\n" +
	"\x0eparameter_size\x18\x05 \x01(\tR\rparameterSize\x12-\n" +
	"\x12quantization_level\x18\x06 \x01(\tR\x11quantizationLevel\"\xc0\x01\n" +
	"\x0fOllamaModelData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1f\n" +
	"\vmodified_at\x18\x03 \x01(\tR\n" +
	"modifiedAt\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x16\n" +
	"\x06digest\x18\x05 \x01(\tR\x06digest\x126\n" +
	"\adetails\x18\x06 \x01(\v2\x1c.downlink.OllamaModelDetailsR\adetails\"I\n" +
	"\x14OllamaModelsResponse\x121\n" +
	"\x06models\x18\x01 \x03(\v2\x19.downlink.OllamaModelDataR\x06models2\xac\x06\n" +
	"\vLLMsService\x12X\n" +
	"\x0fGetLLMProviders\x12 .downlink.GetLLMProvidersRequest\x1a!.downlink.GetLLMProvidersResponse\"\x00\x12O\n" +
	"\x10SaveLLMProviders\x12!.downlink.SaveLLMProvidersRequest\x1a\x16.google.protobuf.Empty\"\x00\x12U\n" +
	"\x12GetAvailableModels\x12#.downlink.GetAvailableModelsRequest\x1a\x18.downlink.ModelsResponse\"\x00\x12\x88\x01\n" +
	"\x1fAnalyzeArticleWithProviderModel\x120.downlink.AnalyzeArticleWithProviderModelRequest\x1a1.downlink.AnalyzeArticleWithProviderModelResponse\"\x00\x12U\n" +
	"\x0eAnalyzeArticle\x12\x1f.downlink.AnalyzeArticleRequest\x1a .downlink.AnalyzeArticleResponse\"\x00\x12^\n" +
	"\x11GetAnalysisConfig\x12\".downlink.GetAnalysisConfigRequest\x1a#.downlink.GetAnalysisConfigResponse\"\x00\x12j\n" +
	"\x15PreviewAnalysisPrompt\x12&.downlink.PreviewAnalysisPromptRequest\x1a'.downlink.PreviewAnalysisPromptResponse\"\x00\x12m\n" +
	"\x14StreamAnalyzeArticle\x120.downlink.AnalyzeArticleWithProviderModelRequest\x1a\x1f.downlink.AnalysisProgressEvent\"\x000\x01B\tZ\aprotos/b\x06proto3"

var (
	file_llms_proto_rawDescOnce sync.Once
	file_llms_proto_rawDescData []byte
)

func file_llms_proto_rawDescGZIP() []byte {
	file_llms_proto_rawDescOnce.Do(func() {
		file_llms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llms_proto_rawDesc), len(file_llms_proto_rawDesc)))
	})
	return file_llms_proto_rawDescData
}

var file_llms_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_llms_proto_goTypes = []any{
	(*GetAnalysisConfigRequest)(nil),                // 0: downlink.GetAnalysisConfigRequest
	(*GetAnalysisConfigResponse)(nil),               // 1: downlink.GetAnalysisConfigResponse
	(*GetLLMProvidersRequest)(nil),                  // 2: downlink.GetLLMProvidersRequest
	(*GetLLMProvidersResponse)(nil),                 // 3: downlink.GetLLMProvidersResponse
	(*SaveLLMProvidersRequest)(nil),                 // 4: downlink.SaveLLMProvidersRequest
	(*GetAvailableModelsRequest)(nil),               // 5: downlink.GetAvailableModelsRequest
	(*ModelInfo)(nil),                               // 6: downlink.ModelInfo
	(*AnalyzeArticleWithProviderModelRequest)(nil),  // 7: downlink.AnalyzeArticleWithProviderModelRequest
	(*AnalyzeArticleWithProviderModelResponse)(nil), // 8: downlink.AnalyzeArticleWithProviderModelResponse
	(*AnalyzeArticleRequest)(nil),                   // 9: downlink.AnalyzeArticleRequest
	(*AnalyzeArticleResponse)(nil),                  // 10: downlink.AnalyzeArticleResponse
	(*PreviewAnalysisPromptRequest)(nil),            // 11: downlink.PreviewAnalysisPromptRequest
	(*PreviewAnalysisPromptResponse)(nil),           // 12: downlink.PreviewAnalysisPromptResponse
	(*AnalysisProgressEvent)(nil),                   // 13: downlink.AnalysisProgressEvent
	(*GenericLLMRequest)(nil),                       // 14: downlink.GenericLLMRequest
	(*Message)(nil),                                 // 15: downlink.Message
	(*OllamaRequest)(nil),                           // 16: downlink.OllamaRequest
	(*OllamaResponse)(nil),                          // 17: downlink.OllamaResponse
	(*OpenAIRequest)(nil),                           // 18: downlink.OpenAIRequest
	(*OpenAIChoice)(nil),                            // 19: downlink.OpenAIChoice
	(*OpenAIResponse)(nil),                          // 20: downlink.OpenAIResponse
	(*AnthropicRequest)(nil),                        // 21: downlink.AnthropicRequest
	(*AnthropicContentItem)(nil),                    // 22: downlink.AnthropicContentItem
	(*AnthropicResponse)(nil),                       // 23: downlink.AnthropicResponse
	(*ModelsResponse)(nil),                          // 24: downlink.ModelsResponse
	(*OpenAIModelData)(nil),                         // 25: downlink.OpenAIModelData
	(*OpenAIModelsResponse)(nil),                    // 26: downlink.OpenAIModelsResponse
	(*AnthropicModelData)(nil),                      // 27: downlink.AnthropicModelData
	(*AnthropicModelsResponse)(nil),                 // 28: downlink.AnthropicModelsResponse
	(*OllamaModelDetails)(nil),                      // 29: downlink.OllamaModelDetails
	(*OllamaModelData)(nil),                         // 30: downlink.OllamaModelData
	(*OllamaModelsResponse)(nil),                    // 31: downlink.OllamaModelsResponse
	(*AnalysisConfig)(nil),                          // 32: downlink.AnalysisConfig
	(*ProviderConfig)(nil),                          // 33: downlink.ProviderConfig
	(*ArticleAnalysis)(nil),                         // 34: downlink.ArticleAnalysis
	(*emptypb.Empty)(nil),                           // 35: google.protobuf.Empty
}
var file_llms_proto_depIdxs = []int32{
	32, // 0: downlink.GetAnalysisConfigResponse.analysis_config:type_name -> downlink.AnalysisConfig
	33, // 1: downlink.GetLLMProvidersResponse.providers:type_name -> downlink.ProviderConfig
	33, // 2: downlink.SaveLLMProvidersRequest.providers:type_name -> downlink.ProviderConfig
	34, // 3: downlink.AnalyzeArticleWithProviderModelResponse.analysis:type_name -> downlink.ArticleAnalysis
	34, // 4: downlink.AnalyzeArticleResponse.analysis:type_name -> downlink.ArticleAnalysis
	34, // 5: downlink.AnalysisProgressEvent.analysis:type_name -> downlink.ArticleAnalysis
	15, // 6: downlink.GenericLLMRequest.messages:type_name -> downlink.Message
	15, // 7: downlink.OpenAIRequest.messages:type_name -> downlink.Message
	15, // 8: downlink.OpenAIChoice.message:type_name -> downlink.Message
	19, // 9: downlink.OpenAIResponse.choices:type_name -> downlink.OpenAIChoice
	15, // 10: downlink.AnthropicRequest.messages:type_name -> downlink.Message
	22, // 11: downlink.AnthropicResponse.content:type_name -> downlink.AnthropicContentItem
	6,  // 12: downlink.ModelsResponse.models:type_name -> downlink.ModelInfo
	25, // 13: downlink.OpenAIModelsResponse.data:type_name -> downlink.OpenAIModelData
	27, // 14: downlink.AnthropicModelsResponse.data:type_name -> downlink.AnthropicModelData
	29, // 15: downlink.OllamaModelData.details:type_name -> downlink.OllamaModelDetails
	30, // 16: downlink.OllamaModelsResponse.models:type_name -> downlink.OllamaModelData
	2,  // 17: downlink.LLMsService.GetLLMProviders:input_type -> downlink.GetLLMProvidersRequest
	4,  // 18: downlink.LLMsService.SaveLLMProviders:input_type -> downlink.SaveLLMProvidersRequest
	5,  // 19: downlink.LLMsService.GetAvailableModels:input_type -> downlink.GetAvailableModelsRequest
	7,  // 20: downlink.LLMsService.AnalyzeArticleWithProviderModel:input_type -> downlink.AnalyzeArticleWithProviderModelRequest
	9,  // 21: downlink.LLMsService.AnalyzeArticle:input_type -> downlink.AnalyzeArticleRequest
	0,  // 22: downlink.LLMsService.GetAnalysisConfig:input_type -> downlink.GetAnalysisConfigRequest
	11, // 23: downlink.LLMsService.PreviewAnalysisPrompt:input_type -> downlink.PreviewAnalysisPromptRequest
	7,  // 24: downlink.LLMsService.StreamAnalyzeArticle:input_type -> downlink.AnalyzeArticleWithProviderModelRequest
	3,  // 25: downlink.LLMsService.GetLLMProviders:output_type -> downlink.GetLLMProvidersResponse
	35, // 26: downlink.LLMsService.SaveLLMProviders:output_type -> google.protobuf.Empty
	24, // 27: downlink.LLMsService.GetAvailableModels:output_type -> downlink.ModelsResponse
	8,  // 28: downlink.LLMsService.AnalyzeArticleWithProviderModel:output_type -> downlink.AnalyzeArticleWithProviderModelResponse
	10, // 29: downlink.LLMsService.AnalyzeArticle:output_type -> downlink.AnalyzeArticleResponse
	1,  // 30: downlink.LLMsService.GetAnalysisConfig:output_type -> downlink.GetAnalysisConfigResponse
	12, // 31: downlink.LLMsService.PreviewAnalysisPrompt:output_type -> downlink.PreviewAnalysisPromptResponse
	13, // 32: downlink.LLMsService.StreamAnalyzeArticle:output_type -> downlink.AnalysisProgressEvent
	25, // [25:33] is the sub-list for method output_type
	17, // [17:25] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_llms_proto_init() }
func file_llms_proto_init() {
	if File_llms_proto != nil {
		return
	}
	file_config_proto_init()
	file_analysis_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llms_proto_rawDesc), len(file_llms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llms_proto_goTypes,
		DependencyIndexes: file_llms_proto_depIdxs,
		MessageInfos:      file_llms_proto_msgTypes,
	}.Build()
	File_llms_proto = out.File
	file_llms_proto_goTypes = nil
	file_llms_proto_depIdxs = nil
}
