// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: profiles.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ApplyProfilesRequest carries the raw profiles.yml content. The server parses
// it with the same schema as the startup apply, so models.ProfileConfig stays
// the single definition of the file format (no proto mirror to drift).
type ApplyProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfilesYaml  string                 `protobuf:"bytes,1,opt,name=profiles_yaml,json=profilesYaml,proto3" json:"profiles_yaml,omitempty"`
	DryRun        bool                   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"` // when true, compute the plan but make no changes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyProfilesRequest) Reset() {
	*x = ApplyProfilesRequest{}
	mi := &file_profiles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyProfilesRequest) ProtoMessage() {}

func (x *ApplyProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyProfilesRequest.ProtoReflect.Descriptor instead.
func (*ApplyProfilesRequest) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyProfilesRequest) GetProfilesYaml() string {
	if x != nil {
		return x.ProfilesYaml
	}
	return ""
}

func (x *ApplyProfilesRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

// ApplyProfilesResponse reports the (would-be, when dry_run) reconciliation
// outcome. All lists carry profile slugs; warnings are human-readable
// "slug: problem" lines from config validation.
type ApplyProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       []string               `protobuf:"bytes,1,rep,name=created,proto3" json:"created,omitempty"`
	Updated       []string               `protobuf:"bytes,2,rep,name=updated,proto3" json:"updated,omitempty"`
	Disabled      []string               `protobuf:"bytes,3,rep,name=disabled,proto3" json:"disabled,omitempty"`
	Skipped       []string               `protobuf:"bytes,4,rep,name=skipped,proto3" json:"skipped,omitempty"`
	Warnings      []string               `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyProfilesResponse) Reset() {
	*x = ApplyProfilesResponse{}
	mi := &file_profiles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyProfilesResponse) ProtoMessage() {}

func (x *ApplyProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyProfilesResponse.ProtoReflect.Descriptor instead.
func (*ApplyProfilesResponse) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyProfilesResponse) GetCreated() []string {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *ApplyProfilesResponse) GetUpdated() []string {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *ApplyProfilesResponse) GetDisabled() []string {
	if x != nil {
		return x.Disabled
	}
	return nil
}

func (x *ApplyProfilesResponse) GetSkipped() []string {
	if x != nil {
		return x.Skipped
	}
	return nil
}

func (x *ApplyProfilesResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// ListProfilesRequest is the request for the ListProfiles method.
type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_profiles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{2}
}

// ProfileSummary is one stored profile, trimmed for CLI display.
type ProfileSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	OutputSubdir  string                 `protobuf:"bytes,7,opt,name=output_subdir,json=outputSubdir,proto3" json:"output_subdir,omitempty"`
	Layout        string                 `protobuf:"bytes,8,opt,name=layout,proto3" json:"layout,omitempty"`
	Theme         string                 `protobuf:"bytes,9,opt,name=theme,proto3" json:"theme,omitempty"`
	FeedCount     int32                  `protobuf:"varint,10,opt,name=feed_count,json=feedCount,proto3" json:"feed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileSummary) Reset() {
	*x = ProfileSummary{}
	mi := &file_profiles_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileSummary) ProtoMessage() {}

func (x *ProfileSummary) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileSummary.ProtoReflect.Descriptor instead.
func (*ProfileSummary) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{3}
}

func (x *ProfileSummary) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ProfileSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProfileSummary) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ProfileSummary) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ProfileSummary) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *ProfileSummary) GetOutputSubdir() string {
	if x != nil {
		return x.OutputSubdir
	}
	return ""
}

func (x *ProfileSummary) GetLayout() string {
	if x != nil {
		return x.Layout
	}
	return ""
}

func (x *ProfileSummary) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *ProfileSummary) GetFeedCount() int32 {
	if x != nil {
		return x.FeedCount
	}
	return 0
}

// ListProfilesResponse is the response for the ListProfiles method.
type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*ProfileSummary      `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_profiles_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{4}
}

func (x *ListProfilesResponse) GetProfiles() []*ProfileSummary {
	if x != nil {
		return x.Profiles
	}
	return nil
}

var File_profiles_proto protoreflect.FileDescriptor

const file_profiles_proto_rawDesc = "" +
	"\n" +
	"\x0eprofiles.proto\x12\bdownlink\"T\n" +
	"\x14ApplyProfilesRequest\x12#\n" +
	"\rprofiles_yaml\x18\x01 \x01(\tR\fprofilesYaml\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\"\x9d\x01\n" +
	"\x15ApplyProfilesResponse\x12\x18\n" +
	"\acreated\x18\x01 \x03(\tR\acreated\x12\x18\n" +
	"\aupdated\x18\x02 \x03(\tR\aupdated\x12\x1a\n" +
	"\bdisabled\x18\x03 \x03(\tR\bdisabled\x12\x18\n" +
	"\askipped\x18\x04 \x03(\tR\askipped\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings\"\x15\n" +
	"\x13ListProfilesRequest\"\x99\x02\n" +
	"\x0eProfileSummary\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\x12#\n" +
	"\routput_subdir\x18\a \x01(\tR\foutputSubdir\x12\x16\n" +
	"\x06layout\x18\b \x01(\tR\x06layout\x12\x14\n" +
	"\x05theme\x18\t \x01(\tR\x05theme\x12\x1d\n" +
	"\n" +
	"feed_count\x18\n" +
	" \x01(\x05R\tfeedCount\"L\n" +
	"\x14ListProfilesResponse\x124\n" +
	"\bprofiles\x18\x01 \x03(\v2\x18.downlink.ProfileSummaryR\bprofiles2\xb6\x01\n" +
	"\x0fProfilesService\x12R\n" +
	"\rApplyProfiles\x12\x1e.downlink.ApplyProfilesRequest\x1a\x1f.downlink.ApplyProfilesResponse\"\x00\x12O\n" +
	"\fListProfiles\x12\x1d.downlink.ListProfilesRequest\x1a\x1e.downlink.ListProfilesResponse\"\x00B\tZ\aprotos/b\x06proto3"

var (
	file_profiles_proto_rawDescOnce sync.Once
	file_profiles_proto_rawDescData []byte
)

func file_profiles_proto_rawDescGZIP() []byte {
	file_profiles_proto_rawDescOnce.Do(func() {
		file_profiles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profiles_proto_rawDesc), len(file_profiles_proto_rawDesc)))
	})
	return file_profiles_proto_rawDescData
}

var file_profiles_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_profiles_proto_goTypes = []any{
	(*ApplyProfilesRequest)(nil),  // 0: downlink.ApplyProfilesRequest
	(*ApplyProfilesResponse)(nil), // 1: downlink.ApplyProfilesResponse
	(*ListProfilesRequest)(nil),   // 2: downlink.ListProfilesRequest
	(*ProfileSummary)(nil),        // 3: downlink.ProfileSummary
	(*ListProfilesResponse)(nil),  // 4: downlink.ListProfilesResponse
}
var file_profiles_proto_depIdxs = []int32{
	3, // 0: downlink.ListProfilesResponse.profiles:type_name -> downlink.ProfileSummary
	0, // 1: downlink.ProfilesService.ApplyProfiles:input_type -> downlink.ApplyProfilesRequest
	2, // 2: downlink.ProfilesService.ListProfiles:input_type -> downlink.ListProfilesRequest
	1, // 3: downlink.ProfilesService.ApplyProfiles:output_type -> downlink.ApplyProfilesResponse
	4, // 4: downlink.ProfilesService.ListProfiles:output_type -> downlink.ListProfilesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_profiles_proto_init() }
func file_profiles_proto_init() {
	if File_profiles_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profiles_proto_rawDesc), len(file_profiles_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profiles_proto_goTypes,
		DependencyIndexes: file_profiles_proto_depIdxs,
		MessageInfos:      file_profiles_proto_msgTypes,
	}.Build()
	File_profiles_proto = out.File
	file_profiles_proto_goTypes = nil
	file_profiles_proto_depIdxs = nil
}
